// Copy for the real-order screens (workspace, new order, settings, KDS), in
// English and Arabic. Kept beside the entity rather than in packages/i18n
// because that package's dictionaries are shared files other work owns; the
// keys are namespaced so they can be merged there verbatim later.
import { useI18n } from "@/app/providers/i18n-provider";

const EN = {
  "common.loading": "Loading…",
  "common.saving": "Saving…",
  "common.save": "Save",
  "common.cancel": "Cancel",
  "common.confirm": "Confirm",
  "common.dismiss": "Dismiss",
  "common.edit": "Edit",
  "common.back": "Back",
  "common.next": "Next",

  "status.New": "New",
  "status.Accepted": "Accepted",
  "status.Preparing": "Preparing",
  "status.Ready": "Ready",
  "status.Served": "Served",
  "status.Completed": "Completed",
  "status.Cancelled": "Cancelled",
  "status.Voided": "Voided",

  "lineStatus.Pending": "Pending",
  "lineStatus.Preparing": "Preparing",
  "lineStatus.Ready": "Ready",
  "lineStatus.Served": "Served",
  "lineStatus.Cancelled": "Cancelled",
  "lineStatus.Voided": "Voided",
  "lineStatus.Wasted": "Wasted",
  "lineStatus.to.Preparing": "Start",
  "lineStatus.to.Ready": "Mark ready",
  "lineStatus.to.Served": "Mark served",

  "workspace.status": "Status:",
  "workspace.payment": "Payment:",
  "workspace.captured": "Captured:",
  "workspace.refunded": "Refunded:",

  "approval.pinOptional": "Manager PIN (if required)",
  "approval.pinRequired": "Manager PIN (required)",
  "approval.neededHint": "enter a manager PIN and try again.",

  "reason.label": "Reason",
  "reason.note": "Note (optional)",
  "reason.choose": "Choose a reason",
  "reason.none": "No reasons configured",

  "lifecycle.accept": "Accept order",
  "lifecycle.all.Preparing": "Start all",
  "lifecycle.all.Ready": "All ready",
  "lifecycle.all.Served": "All served",
  "lifecycle.complete": "Complete order",
  "lifecycle.completeBlocked": "Can't complete yet — {amount} is still due.",
  "lifecycle.transfer": "Move table",
  "lifecycle.currentPlace": "Currently at: {place}",
  "lifecycle.noPlace": "no table",
  "lifecycle.detach": "Detach from table",
  "lifecycle.moveHere": "Move here",
  "lifecycle.reorder": "Re-order",

  "lines.title": "Items ({n})",
  "lines.addItems": "Add items",
  "lines.addToOrder": "Add to order",
  "lines.noCatalog": "This order has no catalog to add from.",
  "lines.quantity": "Quantity",
  "lines.remove": "Remove",
  "lines.wasted": "{n} wasted",
  "lines.selected": "{n} selected",
  "lines.cancelSelected": "Cancel selected",
  "lines.voidSelected": "Void selected",
  "lines.cancelHint": "Started items can only be voided.",

  "discount.add": "Discount",
  "discount.remove": "Remove discount",
  "discount.orderAdd": "Order discount",
  "discount.orderRemove": "Remove order discount",
  "discount.kind": "Type",
  "discount.percent": "Percent %",
  "discount.amount": "Amount ({currency})",
  "discount.value": "Value",
  "discount.apply": "Apply discount",
  "discount.applied": "Discount {value} (−{amount})",
  "discount.orderApplied": "Order discount {value} (−{amount})",

  "details.title": "Customer & details",
  "details.attendees": "Guests",
  "details.fulfilment": "Fulfilment",
  "details.deliveryAddress": "Delivery address",
  "details.customerNote": "Customer note",
  "details.internalNote": "Internal note",
  "details.tags": "Tags (comma separated)",
  "details.capacityWarning": "Party of {party} is larger than the table ({capacity}).",

  "contact.name": "Customer name",
  "contact.phone": "Phone",
  "contact.email": "Email",
  "contact.externalRef": "External reference",

  "payments.title": "Payments",
  "payments.balance": "Balance due {amount}",
  "payments.empty": "No payments yet.",
  "payments.expires": "expires {when}",
  "payments.openLink": "Open link",
  "payments.refresh": "Check status",
  "payments.cancelLink": "Cancel link",
  "payments.createLink": "Payment link",
  "payments.linkAmount": "Amount (blank = {amount})",
  "payments.gratuity": "Tip",
  "payments.issueLink": "Issue link",

  "refunds.title": "Refunds",
  "refunds.empty": "No refunds.",
  "refunds.isRetry": "retry",
  "refunds.retry": "Retry",
  "refunds.retryNow": "Retry refund",

  "wastage.title": "Wastage",
  "wastage.empty": "Nothing recorded as wasted.",
  "wastage.offBill": "taken off the bill",
  "wastage.absorbed": "absorbed by business",
  "wastage.cost": "cost {amount}",

  "activity.title": "Activity",
  "activity.empty": "No activity yet.",
  "activity.system": "System",

  "receipt.send": "Email receipt",
  "receipt.email": "Send to",
  "receipt.emailPlaceholder": "Leave blank to use the customer's email",
  "receipt.submit": "Send receipt",
  "receipt.queued": "Receipt queued — the activity log will show when it is sent.",

  "place.floor": "Floor",
  "place.table": "Table",
  "place.chooseFloor": "Choose a floor",
  "place.noFloors": "No published floor plans",
  "place.noTable": "No table",

  "picker.search": "Search items",
  "picker.empty": "No items match.",
  "picker.unavailable": "Not available now",
  "picker.notForFulfilment": "Not offered for this fulfilment",
  "picker.hasOptions": "Has options",
  "picker.pickRange": "choose {min}–{max}",
  "picker.pickOne": "choose one",
  "picker.optional": "optional",
  "picker.note": "Note",
  "picker.optionsInvalid": "Check your choice for “{group}”.",
  "picker.add": "Add to order",

  "cart.title": "Order ({n} items)",
  "cart.empty": "No items yet.",
  "cart.remove": "Remove",
  "cart.estimate": "Estimate",
  "cart.serverPrices": "Final prices, tax and service charge are calculated when the order is placed.",

  "newOrder.title": "New order",
  "newOrder.reorderTitle": "Re-order",
  "newOrder.subtitle": "Choose a channel and catalog, add items, then place the order.",
  "newOrder.step.setup": "Channel",
  "newOrder.step.items": "Items",
  "newOrder.step.details": "Details",
  "newOrder.source": "Channel",
  "newOrder.catalog": "Catalog",
  "newOrder.chooseCatalog": "Choose a catalog",
  "newOrder.noCatalogs": "Nothing published for this channel",
  "newOrder.fulfilment": "Fulfilment",
  "newOrder.submit": "Place order",
  "newOrder.unavailableLines": "Some items from the original order can no longer be sold:",

  "settings.title": "Order settings",
  "settings.pricing": "Tax & service",
  "settings.taxRate": "Tax rate %",
  "settings.serviceCharge": "Service charge %",
  "settings.timeZone": "Time zone",
  "settings.taxInclusive": "Prices include tax",
  "settings.approvals": "Approvals",
  "settings.approveVoid": "Void needs a manager PIN",
  "settings.approveCancel": "Cancel needs a manager PIN",
  "settings.approveWastage": "Wastage needs a manager PIN",
  "settings.discountThreshold": "Discount without PIN up to",
  "settings.refundThreshold": "Refund without PIN up to",
  "settings.refundWindow": "Refund window (days)",
  "settings.linkLifetime": "Payment link lifetime (hours)",
  "settings.receiptTemplate": "Receipt template",
  "settings.reasons": "Reason codes",
  "settings.reasonsHint": "Comma separated, lower-case codes (e.g. customer-request, mistake).",
  "settings.cancelReasonCodes": "Cancel reasons",
  "settings.voidReasonCodes": "Void reasons",
  "settings.refundReasonCodes": "Refund reasons",
  "settings.wastageReasonCodes": "Wastage reasons",
  "settings.discountReasonCodes": "Discount reasons",
  "settings.sources": "Order channels",
  "settings.platformSource": "platform",
  "settings.enabled": "Enabled",
  "settings.autoAccept": "Auto-accept",
  "settings.newSourceCode": "New channel code",
  "settings.newSourceName": "Name",
  "settings.addSource": "Add channel",
  "settings.sourceCodeInvalid": "A channel code is lower-case letters, digits and hyphens (2–31 characters).",
  "settings.sourceCodeTaken": "That channel code already exists.",

  "page.newOrder": "New order",
  "page.settings": "Settings",
  "page.unavailable": "Orders are not available for this business (the Order module is not enabled or you lack permission).",
  "page.loadFailed": "Couldn't refresh orders: {message}",

  "kds.title": "Kitchen Display",
  "kds.active": "{n} active",
  "kds.col.new": "New",
  "kds.col.preparing": "Preparing",
  "kds.col.ready": "Ready",
  "kds.noTickets": "No tickets",
  "kds.accept": "Accept",
  "kds.bump.Preparing": "Start",
  "kds.bump.Ready": "Ready",
  "kds.bump.Served": "Served",
  "kds.takeaway": "No table",
  "kds.loading": "Loading orders…",
  "kds.signedOut": "Sign in to a business to see its orders.",
} as const;

export type OrderTextKey = keyof typeof EN;

const AR: Record<OrderTextKey, string> = {
  "common.loading": "جارٍ التحميل…",
  "common.saving": "جارٍ الحفظ…",
  "common.save": "حفظ",
  "common.cancel": "إلغاء",
  "common.confirm": "تأكيد",
  "common.dismiss": "إخفاء",
  "common.edit": "تعديل",
  "common.back": "رجوع",
  "common.next": "التالي",

  "status.New": "جديد",
  "status.Accepted": "مقبول",
  "status.Preparing": "قيد التحضير",
  "status.Ready": "جاهز",
  "status.Served": "تم التقديم",
  "status.Completed": "مكتمل",
  "status.Cancelled": "ملغى",
  "status.Voided": "مُبطل",

  "lineStatus.Pending": "بانتظار",
  "lineStatus.Preparing": "قيد التحضير",
  "lineStatus.Ready": "جاهز",
  "lineStatus.Served": "تم التقديم",
  "lineStatus.Cancelled": "ملغى",
  "lineStatus.Voided": "مُبطل",
  "lineStatus.Wasted": "هالك",
  "lineStatus.to.Preparing": "ابدأ",
  "lineStatus.to.Ready": "جاهز",
  "lineStatus.to.Served": "تم التقديم",

  "workspace.status": "الحالة:",
  "workspace.payment": "الدفع:",
  "workspace.captured": "المحصّل:",
  "workspace.refunded": "المسترد:",

  "approval.pinOptional": "رمز المدير (عند الحاجة)",
  "approval.pinRequired": "رمز المدير (مطلوب)",
  "approval.neededHint": "أدخل رمز المدير وحاول مرة أخرى.",

  "reason.label": "السبب",
  "reason.note": "ملاحظة (اختياري)",
  "reason.choose": "اختر السبب",
  "reason.none": "لا توجد أسباب مُعدّة",

  "lifecycle.accept": "قبول الطلب",
  "lifecycle.all.Preparing": "ابدأ الكل",
  "lifecycle.all.Ready": "الكل جاهز",
  "lifecycle.all.Served": "تم تقديم الكل",
  "lifecycle.complete": "إكمال الطلب",
  "lifecycle.completeBlocked": "لا يمكن الإكمال بعد — ما زال مستحقًا {amount}.",
  "lifecycle.transfer": "نقل الطاولة",
  "lifecycle.currentPlace": "الموقع الحالي: {place}",
  "lifecycle.noPlace": "بدون طاولة",
  "lifecycle.detach": "فصل عن الطاولة",
  "lifecycle.moveHere": "نقل هنا",
  "lifecycle.reorder": "إعادة الطلب",

  "lines.title": "الأصناف ({n})",
  "lines.addItems": "إضافة أصناف",
  "lines.addToOrder": "إضافة للطلب",
  "lines.noCatalog": "لا يوجد كتالوج لهذا الطلب للإضافة منه.",
  "lines.quantity": "الكمية",
  "lines.remove": "حذف",
  "lines.wasted": "{n} هالك",
  "lines.selected": "{n} محدد",
  "lines.cancelSelected": "إلغاء المحدد",
  "lines.voidSelected": "إبطال المحدد",
  "lines.cancelHint": "الأصناف التي بدأ تحضيرها يمكن إبطالها فقط.",

  "discount.add": "خصم",
  "discount.remove": "إزالة الخصم",
  "discount.orderAdd": "خصم على الطلب",
  "discount.orderRemove": "إزالة خصم الطلب",
  "discount.kind": "النوع",
  "discount.percent": "نسبة %",
  "discount.amount": "مبلغ ({currency})",
  "discount.value": "القيمة",
  "discount.apply": "تطبيق الخصم",
  "discount.applied": "خصم {value} (−{amount})",
  "discount.orderApplied": "خصم الطلب {value} (−{amount})",

  "details.title": "العميل والتفاصيل",
  "details.attendees": "عدد الضيوف",
  "details.fulfilment": "طريقة الاستلام",
  "details.deliveryAddress": "عنوان التوصيل",
  "details.customerNote": "ملاحظة العميل",
  "details.internalNote": "ملاحظة داخلية",
  "details.tags": "وسوم (مفصولة بفواصل)",
  "details.capacityWarning": "عدد الضيوف {party} أكبر من سعة الطاولة ({capacity}).",

  "contact.name": "اسم العميل",
  "contact.phone": "الجوال",
  "contact.email": "البريد الإلكتروني",
  "contact.externalRef": "مرجع خارجي",

  "payments.title": "المدفوعات",
  "payments.balance": "المتبقي {amount}",
  "payments.empty": "لا توجد مدفوعات بعد.",
  "payments.expires": "ينتهي {when}",
  "payments.openLink": "فتح الرابط",
  "payments.refresh": "تحقق من الحالة",
  "payments.cancelLink": "إلغاء الرابط",
  "payments.createLink": "رابط دفع",
  "payments.linkAmount": "المبلغ (فارغ = {amount})",
  "payments.gratuity": "إكرامية",
  "payments.issueLink": "إصدار الرابط",

  "refunds.title": "المستردات",
  "refunds.empty": "لا توجد مستردات.",
  "refunds.isRetry": "إعادة محاولة",
  "refunds.retry": "إعادة المحاولة",
  "refunds.retryNow": "إعادة محاولة الاسترداد",

  "wastage.title": "الهالك",
  "wastage.empty": "لم يُسجّل أي هالك.",
  "wastage.offBill": "خُصم من الفاتورة",
  "wastage.absorbed": "تتحمله المنشأة",
  "wastage.cost": "التكلفة {amount}",

  "activity.title": "السجل",
  "activity.empty": "لا يوجد نشاط بعد.",
  "activity.system": "النظام",

  "receipt.send": "إرسال الإيصال",
  "receipt.email": "إرسال إلى",
  "receipt.emailPlaceholder": "اتركه فارغًا لاستخدام بريد العميل",
  "receipt.submit": "إرسال الإيصال",
  "receipt.queued": "تمت جدولة الإيصال — سيظهر في السجل عند إرساله.",

  "place.floor": "المخطط",
  "place.table": "الطاولة",
  "place.chooseFloor": "اختر المخطط",
  "place.noFloors": "لا توجد مخططات منشورة",
  "place.noTable": "بدون طاولة",

  "picker.search": "ابحث عن صنف",
  "picker.empty": "لا توجد أصناف مطابقة.",
  "picker.unavailable": "غير متاح الآن",
  "picker.notForFulfilment": "غير متاح لطريقة الاستلام هذه",
  "picker.hasOptions": "له خيارات",
  "picker.pickRange": "اختر {min}–{max}",
  "picker.pickOne": "اختر واحدًا",
  "picker.optional": "اختياري",
  "picker.note": "ملاحظة",
  "picker.optionsInvalid": "راجع اختيارك في «{group}».",
  "picker.add": "إضافة للطلب",

  "cart.title": "الطلب ({n} أصناف)",
  "cart.empty": "لا توجد أصناف بعد.",
  "cart.remove": "حذف",
  "cart.estimate": "تقديري",
  "cart.serverPrices": "الأسعار النهائية والضريبة ورسوم الخدمة تُحسب عند تسجيل الطلب.",

  "newOrder.title": "طلب جديد",
  "newOrder.reorderTitle": "إعادة الطلب",
  "newOrder.subtitle": "اختر القناة والكتالوج، أضف الأصناف، ثم سجّل الطلب.",
  "newOrder.step.setup": "القناة",
  "newOrder.step.items": "الأصناف",
  "newOrder.step.details": "التفاصيل",
  "newOrder.source": "القناة",
  "newOrder.catalog": "الكتالوج",
  "newOrder.chooseCatalog": "اختر الكتالوج",
  "newOrder.noCatalogs": "لا يوجد منشور لهذه القناة",
  "newOrder.fulfilment": "طريقة الاستلام",
  "newOrder.submit": "تسجيل الطلب",
  "newOrder.unavailableLines": "بعض أصناف الطلب الأصلي لم تعد متاحة للبيع:",

  "settings.title": "إعدادات الطلبات",
  "settings.pricing": "الضريبة والخدمة",
  "settings.taxRate": "نسبة الضريبة %",
  "settings.serviceCharge": "رسوم الخدمة %",
  "settings.timeZone": "المنطقة الزمنية",
  "settings.taxInclusive": "الأسعار شاملة الضريبة",
  "settings.approvals": "الموافقات",
  "settings.approveVoid": "الإبطال يتطلب رمز المدير",
  "settings.approveCancel": "الإلغاء يتطلب رمز المدير",
  "settings.approveWastage": "الهالك يتطلب رمز المدير",
  "settings.discountThreshold": "خصم بدون رمز حتى",
  "settings.refundThreshold": "استرداد بدون رمز حتى",
  "settings.refundWindow": "مهلة الاسترداد (أيام)",
  "settings.linkLifetime": "صلاحية رابط الدفع (ساعات)",
  "settings.receiptTemplate": "قالب الإيصال",
  "settings.reasons": "رموز الأسباب",
  "settings.reasonsHint": "رموز بأحرف إنجليزية صغيرة مفصولة بفواصل (مثل customer-request, mistake).",
  "settings.cancelReasonCodes": "أسباب الإلغاء",
  "settings.voidReasonCodes": "أسباب الإبطال",
  "settings.refundReasonCodes": "أسباب الاسترداد",
  "settings.wastageReasonCodes": "أسباب الهالك",
  "settings.discountReasonCodes": "أسباب الخصم",
  "settings.sources": "قنوات الطلب",
  "settings.platformSource": "من المنصة",
  "settings.enabled": "مفعّلة",
  "settings.autoAccept": "قبول تلقائي",
  "settings.newSourceCode": "رمز القناة الجديدة",
  "settings.newSourceName": "الاسم",
  "settings.addSource": "إضافة قناة",
  "settings.sourceCodeInvalid": "رمز القناة أحرف إنجليزية صغيرة وأرقام وشرطات (2–31 حرفًا).",
  "settings.sourceCodeTaken": "رمز القناة موجود بالفعل.",

  "page.newOrder": "طلب جديد",
  "page.settings": "الإعدادات",
  "page.unavailable": "الطلبات غير متاحة لهذه المنشأة (وحدة الطلبات غير مفعّلة أو لا تملك الصلاحية).",
  "page.loadFailed": "تعذّر تحديث الطلبات: {message}",

  "kds.title": "شاشة المطبخ",
  "kds.active": "{n} نشط",
  "kds.col.new": "جديد",
  "kds.col.preparing": "قيد التحضير",
  "kds.col.ready": "جاهز",
  "kds.noTickets": "لا توجد تذاكر",
  "kds.accept": "قبول",
  "kds.bump.Preparing": "ابدأ",
  "kds.bump.Ready": "جاهز",
  "kds.bump.Served": "تم التقديم",
  "kds.takeaway": "بدون طاولة",
  "kds.loading": "جارٍ تحميل الطلبات…",
  "kds.signedOut": "سجّل الدخول لمنشأة لعرض طلباتها.",
};

export function useOrderText(): { tx: (key: OrderTextKey) => string } {
  const { locale } = useI18n();
  const dict: Record<OrderTextKey, string> = locale === "ar" ? AR : EN;
  return { tx: (key: OrderTextKey) => dict[key] ?? key };
}
