// A QR encoder written from scratch, with no dependency, scoped to exactly
// the one shape this page needs: a version-4 symbol (33x33 modules), byte
// mode, error-correction level L, one Reed-Solomon block, mask pattern 0.
// Fixing every one of those removes the general algorithm's version
// selection, multi-block interleaving, and version-information block (that
// only appears from version 7 up) — this is not a general QR encoder.
//
// Clause references are to ISO/IEC 18004:2015, "Information technology —
// Automatic identification and data capture techniques — QR Code bar code
// symbology specification".

const MODULE_COUNT = 33; // §6.3, Table 1 — version 4 size is 4x4 + 17.
const TOTAL_CODEWORDS = 100; // §6.5.1, Table 7 — version 4 total codewords.
const DATA_CODEWORDS = 80; // §6.5.1, Table 9 — version 4, EC level L, data codewords (one block).
const EC_CODEWORDS = TOTAL_CODEWORDS - DATA_CODEWORDS; // 20 EC codewords, Table 9.
const MAX_BYTES = 78; // §6.4.10, Table 7 — version 4-L byte-mode character capacity.

// ---- GF(256) arithmetic, Annex A ----
// The field used for Reed-Solomon is generated by the primitive polynomial
// x^8 + x^4 + x^3 + x^2 + 1 (0x11D) with generator element 2 (Annex A).
const GF_EXP: readonly number[] = (() => {
  const exp = new Array<number>(512);
  let x = 1;
  for (let i = 0; i < 255; i++) {
    exp[i] = x;
    x <<= 1;
    if (x & 0x100) x ^= 0x11d;
  }
  for (let i = 255; i < 512; i++) exp[i] = exp[i - 255];
  return exp;
})();

const GF_LOG: readonly number[] = (() => {
  const log = new Array<number>(256).fill(0);
  for (let i = 0; i < 255; i++) log[GF_EXP[i]] = i;
  return log;
})();

function gfMul(a: number, b: number): number {
  if (a === 0 || b === 0) return 0;
  return GF_EXP[GF_LOG[a] + GF_LOG[b]];
}

// ---- Reed-Solomon generator polynomial, Annex A.2 ----
// The generator for n EC codewords is the product, for i = 0..n-1, of the
// monomial (x - 2^i); subtraction is XOR in GF(256). Coefficients are
// highest-degree first, and the polynomial is monic (leading coefficient 1).
const GENERATOR_POLY: readonly number[] = (() => {
  let poly: number[] = [1];
  for (let i = 0; i < EC_CODEWORDS; i++) {
    const next = new Array<number>(poly.length + 1).fill(0);
    for (let j = 0; j < poly.length; j++) {
      next[j] ^= poly[j]; // the "multiply by x" term: same coefficient, one degree higher
      next[j + 1] ^= gfMul(poly[j], GF_EXP[i]); // the "multiply by alpha^i" term
    }
    poly = next;
  }
  return poly;
})();

/** Polynomial long division of the data codewords (message, shifted left by
 *  EC_CODEWORDS zero bytes) by GENERATOR_POLY over GF(256); the remainder is
 *  the EC codewords. Standard Reed-Solomon encode, §Annex A. */
function reedSolomonRemainder(data: readonly number[]): number[] {
  const result = data.concat(new Array(EC_CODEWORDS).fill(0));
  for (let i = 0; i < data.length; i++) {
    const factor = result[i];
    if (factor !== 0) {
      for (let j = 0; j < GENERATOR_POLY.length; j++) {
        result[i + j] ^= gfMul(GENERATOR_POLY[j], factor);
      }
    }
  }
  return result.slice(data.length);
}

// ---- Format information, §7.9 ----
// 5 data bits: 2-bit EC level indicator (Table 25: L = 01) + 3-bit mask
// pattern reference (000 for mask 0), BCH(15,5)-encoded then XOR-masked.
const FORMAT_DATA_BITS = 0b01000; // EC level L ("01") + mask 0 ("000").
const FORMAT_GENERATOR = 0b10100110111; // §7.9.2 — the (15,5) BCH generator polynomial.
const FORMAT_XOR_MASK = 0b101010000010010; // §7.9.2 — the fixed format-info XOR mask.

function bchRemainder(value: number, generator: number): number {
  let v = value;
  const generatorBits = 32 - Math.clz32(generator);
  while (32 - Math.clz32(v) >= generatorBits) {
    v ^= generator << (32 - Math.clz32(v) - generatorBits);
  }
  return v;
}

const FORMAT_BITS: readonly boolean[] = (() => {
  const shifted = FORMAT_DATA_BITS << 10;
  const remainder = bchRemainder(shifted, FORMAT_GENERATOR);
  const masked = (shifted | remainder) ^ FORMAT_XOR_MASK;
  const bits: boolean[] = [];
  for (let i = 14; i >= 0; i--) bits.push(((masked >> i) & 1) === 1);
  return bits;
})();

// ---- Bit stream, §7.4 ----
function bitsForText(text: string): number[] {
  const bytes = Array.from(new TextEncoder().encode(text));
  if (bytes.length > MAX_BYTES) {
    throw new RangeError(
      `encodeQr: ${bytes.length} bytes exceeds the ${MAX_BYTES}-byte capacity of a version-4 byte-mode symbol at EC level L`
    );
  }

  const bits: number[] = [];
  const push = (value: number, length: number) => {
    for (let i = length - 1; i >= 0; i--) bits.push((value >>> i) & 1);
  };

  push(0b0100, 4); // §7.4.3, Table 2 — byte-mode indicator.
  push(bytes.length, 8); // §7.4.9, Table 3 — 8-bit char-count indicator, versions 1-9.
  for (const b of bytes) push(b, 8);

  const capacityBits = DATA_CODEWORDS * 8;
  const terminatorLen = Math.max(0, Math.min(4, capacityBits - bits.length)); // §7.4.9 — terminator, up to 4 zero bits.
  for (let i = 0; i < terminatorLen; i++) bits.push(0);
  while (bits.length % 8 !== 0) bits.push(0); // pad to a byte boundary.

  return bits;
}

function codewordsForText(text: string): number[] {
  const bits = bitsForText(text);
  const codewords: number[] = [];
  for (let i = 0; i < bits.length; i += 8) {
    let byte = 0;
    for (let j = 0; j < 8; j++) byte = (byte << 1) | bits[i + j];
    codewords.push(byte);
  }

  const PAD_BYTES = [0xec, 0x11] as const; // §7.4.10 — alternating pad codewords.
  for (let i = 0; codewords.length < DATA_CODEWORDS; i++) codewords.push(PAD_BYTES[i % 2]);
  return codewords;
}

// ---- Matrix construction, §6.3 / §7.3 / §7.8 ----
function drawFinder(matrix: boolean[][], isFunction: boolean[][], top: number, left: number) {
  for (let r = -1; r <= 7; r++) {
    for (let c = -1; c <= 7; c++) {
      const row = top + r;
      const col = left + c;
      if (row < 0 || row >= MODULE_COUNT || col < 0 || col >= MODULE_COUNT) continue;
      isFunction[row][col] = true;
      const inPattern = r >= 0 && r <= 6 && c >= 0 && c <= 6;
      matrix[row][col] = inPattern && (r === 0 || r === 6 || c === 0 || c === 6 || (r >= 2 && r <= 4 && c >= 2 && c <= 4));
    }
  }
}

function drawAlignment(matrix: boolean[][], isFunction: boolean[][], centerRow: number, centerCol: number) {
  for (let r = -2; r <= 2; r++) {
    for (let c = -2; c <= 2; c++) {
      const row = centerRow + r;
      const col = centerCol + c;
      isFunction[row][col] = true;
      matrix[row][col] = Math.max(Math.abs(r), Math.abs(c)) !== 1;
    }
  }
}

function drawTiming(matrix: boolean[][], isFunction: boolean[][]) {
  for (let i = 8; i <= MODULE_COUNT - 9; i++) {
    const dark = i % 2 === 0;
    isFunction[6][i] = true;
    matrix[6][i] = dark;
    isFunction[i][6] = true;
    matrix[i][6] = dark;
  }
}

function reserveFormatAreas(matrix: boolean[][], isFunction: boolean[][]) {
  const size = MODULE_COUNT;
  // Copy A, hugging the top-left finder — see placeFormatBits for the layout
  // this mirrors once the real bits are known.
  for (let i = 0; i <= 5; i++) isFunction[8][i] = true;
  isFunction[8][7] = true;
  isFunction[8][8] = true;
  isFunction[7][8] = true;
  for (let i = 9; i <= 14; i++) isFunction[14 - i][8] = true;
  // Copy B, split across the bottom-left and top-right finders.
  for (let i = 0; i <= 7; i++) isFunction[size - 1 - i][8] = true;
  for (let i = 8; i <= 14; i++) isFunction[8][size - 15 + i] = true;
  // The fixed dark module, §7.9.1 — always dark, at (8, 4*version + 9).
  isFunction[8][size - 8] = true;
  matrix[8][size - 8] = true;
}

function placeFormatBits(matrix: boolean[][], bits: readonly boolean[]) {
  const size = MODULE_COUNT;
  for (let i = 0; i <= 5; i++) matrix[8][i] = bits[i];
  matrix[8][7] = bits[6];
  matrix[8][8] = bits[7];
  matrix[7][8] = bits[8];
  for (let i = 9; i <= 14; i++) matrix[14 - i][8] = bits[i];

  for (let i = 0; i <= 7; i++) matrix[size - 1 - i][8] = bits[i];
  for (let i = 8; i <= 14; i++) matrix[8][size - 15 + i] = bits[i];
}

/** Places the 800 data+EC bits into the non-function modules in the standard
 *  two-column, boustrophedon zigzag (§7.7.3), and applies mask pattern 0
 *  (`(row + col) % 2 === 0`, §7.8.2) to every data module as it is placed —
 *  function modules are never masked. */
function placeData(matrix: boolean[][], isFunction: boolean[][], codewords: readonly number[]) {
  const size = MODULE_COUNT;
  const totalBits = codewords.length * 8;
  let bitIndex = 0;
  const nextBit = (): boolean => {
    if (bitIndex >= totalBits) {
      bitIndex++;
      return false;
    }
    const byte = codewords[bitIndex >> 3];
    const bit = (byte >> (7 - (bitIndex & 7))) & 1;
    bitIndex++;
    return bit === 1;
  };

  let upward = true;
  for (let colRight = size - 1; colRight > 0; colRight -= 2) {
    if (colRight === 6) colRight--; // the vertical timing column carries no data.
    for (let i = 0; i < size; i++) {
      const row = upward ? size - 1 - i : i;
      for (let j = 0; j < 2; j++) {
        const col = colRight - j;
        if (isFunction[row][col]) continue;
        const bit = nextBit();
        const mask = (row + col) % 2 === 0;
        matrix[row][col] = bit !== mask; // XOR
      }
    }
    upward = !upward;
  }
}

/** Encodes `text` as a version-4, byte-mode, EC-level-L QR symbol and returns
 *  its 33x33 module matrix — `true` for a dark module. Throws `RangeError`
 *  when `text`'s UTF-8 encoding exceeds the 78-byte capacity of that fixed
 *  shape. */
export function encodeQr(text: string): boolean[][] {
  const dataCodewords = codewordsForText(text);
  const ecCodewords = reedSolomonRemainder(dataCodewords);
  const allCodewords = dataCodewords.concat(ecCodewords);

  const matrix: boolean[][] = Array.from({ length: MODULE_COUNT }, () => new Array(MODULE_COUNT).fill(false));
  const isFunction: boolean[][] = Array.from({ length: MODULE_COUNT }, () => new Array(MODULE_COUNT).fill(false));

  drawFinder(matrix, isFunction, 0, 0);
  drawFinder(matrix, isFunction, 0, MODULE_COUNT - 7);
  drawFinder(matrix, isFunction, MODULE_COUNT - 7, 0);
  drawAlignment(matrix, isFunction, 26, 26); // §Annex E, Table E.1 — the one version-4 alignment pattern.
  drawTiming(matrix, isFunction);
  reserveFormatAreas(matrix, isFunction);

  placeData(matrix, isFunction, allCodewords);
  placeFormatBits(matrix, FORMAT_BITS);

  return matrix;
}
