// Strings for the US-019 (server-backed) parts of the builder. packages/i18n is
// not owned by this slice, so — like ui/versions-modal.tsx — each key falls back
// to this table until the shared dictionary carries it; `t` wins once it does.
import { useCallback } from "react";
import { useI18n } from "@/app/providers/i18n-provider";
import { catalogueText } from "./catalogue-text";

type Table = Record<string, string>;

const EN: Table = {
  // ---- Validation messages (see _shared/validation.ts) ----
  "pl.v.required": "This field is required.",
  "pl.v.minLength": "Enter at least {min} characters.",
  "pl.v.maxLength": "Use {max} characters at most.",
  "pl.v.email": "Enter a valid email address, e.g. name@example.com.",
  "pl.v.hexColor": "Enter a 6-digit hex colour, e.g. #08589D.",
  "pl.v.slug": "Use lowercase letters, numbers and hyphens only.",
  "pl.v.hostname": "Enter a valid domain, e.g. www.example.com.",
  "pl.v.url": "Enter a full address starting with https://.",
  "pl.v.integer": "Enter a whole number.",
  "pl.v.amount": "Enter a valid amount, e.g. 25 or 25.50.",
  "pl.v.min": "Must be {min} or more.",
  "pl.v.max": "Must be {max} or less.",
  "pl.v.rangeOrder": "Max must be greater than or equal to Min.",
  "pl.v.fileType": "This file type is not supported. Use {types}.",
  "pl.v.fileSize": "The file is too large. Maximum size is {max} MB.",
  "pl.v.duplicate": "This value has already been added.",
  "pl.v.fixBeforeNext": "Fix the highlighted fields before continuing.",
  "pl.shell.back": "Back",
  "pl.theme.allThemes": "All Themes",
  // <pl-redesign:theme-en>
  "pl.brand.logoHintFormat": "Recommended: PNG/SVG",
  "pl.brand.logoHintSize": "Size: 512×512px",
  "pl.brand.noLogo": "No logo yet",
  "pl.brand.typographyEn": "Typography (EN)",
  "pl.brand.typographyAr": "Typography (AR)",
  "pl.brand.heroPattern": "Hero Pattern/ Background",
  // <pl-redesign:brand-en>
  "pl.pages.reorderHint": "Drag to reorder pages in your navigation",
  "pl.pages.socialImageType": "PNG, JPG or WebP",
  // <pl-redesign:pages-en>
  "pl.navigation.showInHeader": "Show in Main Navigation (Header)",
  "pl.navigation.showInDrawer": "Show in Mobile Drawer Menu",
  "pl.navigation.stickyHeaderNote": "Keep navigation visible while scrolling",
  "pl.navigation.activeIndicator": "Active page indicator",
  "pl.navigation.activeIndicatorNote": "Highlight current page in navigation",
  "pl.navigation.showIcons": "Show icons in navigation",
  "pl.navigation.showIconsNote": "Display icons next to menu items",
  "pl.navigation.sameTab": "Open links in same tab",
  "pl.navigation.sameTabNote": "Default behavior for menu links",
  "pl.navigation.dragHint": "Drag to reorder pages in your navigation",
  "pl.navigation.tip": "Tip: You can change the order of pages in your navigation",
  "pl.navigation.updatesInstantly": "Navigation updates instantly as you reorder or change visibility.",
  "pl.navigation.url": "Website address",
  "pl.navigation.phoneInvalid": "Enter a valid phone number.",
  // <pl-redesign:navigation-en>
  "pl.customize.insp.enterNumber": "Enter number",
  "pl.customize.insp.min": "MIN",
  "pl.customize.insp.max": "MAX",
  "pl.customize.insp.partySize": "Min / Max Party Size",
  "pl.customize.insp.displayOnHomepage": "Menu Display on Homepage",
  "pl.customize.insp.primaryAction": "Primary Action on Menu CTA",
  "pl.customize.insp.moduleSetting": "Module Setting",
  "pl.customize.insp.widget": "Reservation Widget",
  "pl.customize.insp.widgetNote": "Inline booking form.",
  "pl.customize.insp.button": "Button/Link",
  "pl.customize.insp.buttonNote": "CTA button to open booking",
  "pl.customize.insp.availability": "Availability Preview",
  "pl.customize.insp.nextAvailable": "Show Next Available Time",
  "pl.customize.insp.label": "Label",
  "pl.customize.insp.labelPlaceholder": "Enter label name",
  "pl.customize.insp.targetNote": "Guests are taken to this page",
  "pl.customize.insp.whatsapp": "WhatsApp Notification",
  "pl.customize.insp.sms": "SMS Notification",
  "pl.customize.insp.email": "Email Notification",
  "pl.customize.insp.optional": "(Optional)",
  "pl.customize.menu.connect": "Connect Saved Menu",
  "pl.customize.menu.connectNote": "Choose a menu you have already created in your menu module.",
  "pl.customize.menu.select": "Select menu",
  "pl.customize.menu.meta": "Updated {days} days ago. {items} Items",
  "pl.customize.menu.displayNote": "Choose how your menu appears on the homepage.",
  "pl.customize.menu.highlighted": "Highlighted Dishes",
  "pl.customize.menu.highlightedNote": "Show selected popular dishes",
  "pl.customize.menu.categories": "Menu Categories",
  "pl.customize.menu.categoriesNote": "Show menu categories",
  "pl.customize.menu.preview": "Menu Preview",
  "pl.customize.menu.previewNote": "Show menu preview with link",
  "pl.customize.menu.full": "Full Menu",
  "pl.customize.menu.fullNote": "Show all menu on homepage",
  "pl.customize.menu.primaryNote": "Choose where the main menu CTA button will take customers.",
  "pl.customize.menu.openPage": "Open Menu Page",
  "pl.customize.menu.openPageNote": "Open the full menu page in site.",
  "pl.customize.menu.openDrawer": "Open Menu Drawer",
  "pl.customize.menu.openDrawerNote": "Open menu in a side drawer",
  "pl.customize.menu.openOrdering": "Open Ordering/ Reservations",
  "pl.customize.menu.openOrderingNote": "Go directly to ordering or reservations.",
  "pl.customize.menu.moduleSetting": "Menu & order module setting",
  "pl.customize.menu.moduleSettingNote": "Configure ordering behavior and availability.",
  "pl.customize.menu.orderingMode": "Ordering Mode",
  "pl.customize.menu.modeOrdering": "Ordering",
  "pl.customize.menu.modeReservation": "Reservation",
  "pl.customize.menu.modeView": "View",
  "pl.customize.menu.minOrder": "Min Order",
  "pl.customize.menu.minOrderUnit": "(SAR)",
  "pl.customize.menu.enterPrice": "Enter price",
  "pl.customize.menu.orderAhead": "Order Ahead",
  "pl.customize.menu.orderAheadNote": "Allow customers to place orders for later",
  "pl.customize.menu.prepTime": "Estimated Prep Time",
  "pl.customize.menu.prepTimePlaceholder": "Enter estimated time",
  "pl.customize.menu.prepTimeNote": "Shown to customers during checkout.",
  "pl.customize.menu.serviceAreas": "Services Area",
  "pl.customize.menu.serviceAreasUnit": "(Delivery)",
  "pl.customize.menu.serviceAreasPlaceholder": "Jeddah, Al Salamah, Al Rawdah",
  "pl.customize.menu.taxDisplay": "TAX Display",
  "pl.customize.menu.taxInclusive": "Show prices inclusive of VAT",
  "pl.customize.menu.taxExclusive": "Show prices exclusive of VAT",
  "pl.customize.menu.taxNote": "How prices are displayed to customers.",
  "pl.customize.res.module": "Reservation Module",
  "pl.customize.res.moduleNote": "Enable and configure reservations for your restaurant.",
  "pl.customize.res.enable": "Enable Reservation",
  "pl.customize.res.enableNote": "Allow users to book tables online.",
  "pl.customize.res.active": "Reservation module is active.",
  "pl.customize.res.displayNote": "Choose how your reservations appear on the homepage.",
  "pl.customize.res.primaryNote": "Choose the main action for reservation",
  "pl.customize.res.openForm": "Open reservation form",
  "pl.customize.res.openFormNote": "Guests can book directly on home page",
  "pl.customize.res.availabilityNote": "Show available status on homepage.",
  "pl.customize.res.dateRange": "Date range to check",
  "pl.customize.res.bookingWindow": "Allow bookings up to",
  "pl.customize.res.cutOff": "Cut-Off Time",
  "pl.customize.res.tableHold": "Table Hold Time",
  "pl.customize.res.autoConfirm": "Auto Confirm",
  "pl.customize.res.autoConfirmNote": "Automatically confirm reservations. If disabled, approval is required.",
  "pl.customize.res.deposit": "Deposit",
  "pl.customize.res.depositNote": "Require deposit for bookings",
  "pl.customize.wl.module": "Waitlist Module",
  "pl.customize.wl.moduleNote": "Enable and configure waitlist for your restaurant.",
  "pl.customize.wl.enable": "Enable Waitlist",
  "pl.customize.wl.enableNote": "Guests can join waitlist online.",
  "pl.customize.wl.active": "Waitlist module is active.",
  "pl.customize.wl.primaryNote": "Choose the main action for waitlist",
  "pl.customize.wl.openDrawer": "Open waitlist drawer",
  "pl.customize.wl.openDrawerNote": "Guests join waitlist in a slide-in drawer",
  "pl.customize.wl.availabilityNote": "Show estimated wait time on homepage",
  "pl.customize.wl.format": "Format",
  "pl.customize.wl.format.30min": "30min",
  "pl.customize.wl.format.1h": "1h",
  "pl.customize.wl.queueMethod": "Queue Method",
  "pl.customize.wl.fifo": "First Come, First Served",
  "pl.customize.wl.fifoNote": "Guests are added in order",
  "pl.customize.wl.priority": "Priority Rules",
  "pl.customize.wl.priorityNote": "VIPs, reservations & statuses first",
  "pl.customize.wl.waitTime": "Wait time display",
  "pl.customize.wl.waitTimeNote": "Show estimated wait time",
  "pl.customize.wl.updateInterval": "Update interval",
  "pl.customize.wl.notifications": "Notifications",
  "pl.customize.wl.autoRemove": "Auto Remove",
  "pl.customize.wl.autoRemoveNote": "Remove if not confirmed in",
  "pl.customize.hero.headingPlaceholder": "Enter heading",
  "pl.customize.hero.subheadingPlaceholder": "Enter subheading",
  "pl.customize.hero.primaryCtaPlaceholder": "Enter primary CTA name",
  "pl.customize.hero.secondaryCtaPlaceholder": "Enter secondary CTA name",
  "pl.customize.hero.imageTypes": "PNG, JPG or WebP",
  "pl.customize.hero.chooseAction": "Choose a link or action for this button.",
  "pl.customize.noImage": "No image yet",
  "pl.customize.fixFields": "Fix the highlighted fields before saving.",
  "pl.customize.settingKeyInvalid": "Start with a letter; use letters, numbers, hyphens, underscores and dots only.",
  // <pl-redesign:customize-en>
  "pl.preview.testModeOff": "Test mode is OFF",
  "pl.preview.allCompleted": "All steps completed successfully.",
  "pl.preview.urlLabel": "Preview URL",
  "pl.preview.urlMode": "(Test Mode)",
  "pl.preview.inviteNote": "Share your preview with team or clients.",
  "pl.preview.emailPlaceholder": "Enter your email",
  "pl.preview.canViewTest": "Can View Test",
  "pl.preview.testers": "Tester",
  "pl.preview.labelField": "Link label",
  "pl.preview.optional": "(Optional)",
  "pl.preview.labelPlaceholder": "e.g. For the design team",
  // <pl-redesign:preview-en>
  "pl.publish.checklistTitle": "1- Go-Live Checklist",
  "pl.publish.checklistReady": "Everything looks good, you're ready to publish.",
  "pl.publish.checklistPending": "Finish the items marked Fix, then publish.",
  "pl.publish.check.pages.label": "All pages are published",
  "pl.publish.check.pages.note": "{n} pages",
  "pl.publish.check.navigation.label": "Navigation is set",
  "pl.publish.check.navigation.note": "All menu items linked",
  "pl.publish.check.menu.label": "Menu is connected",
  "pl.publish.check.menu.note": "All menu items linked",
  "pl.publish.check.reservations.label": "Reservation is working",
  "pl.publish.check.reservations.note": "Booking flow active",
  "pl.publish.check.waitlist.label": "Waiting list is working",
  "pl.publish.check.waitlist.note": "Join & notify enabled",
  "pl.publish.check.payments.label": "Payments is configured",
  "pl.publish.check.payments.note": "Moyasar (Test Mode)",
  "pl.publish.check.responsive.label": "Responsive & Arabic",
  "pl.publish.check.responsive.note": "Desktop, Tablet, Mobile, RTL",
  "pl.publish.check.seo.label": "SEO basic settings",
  "pl.publish.check.seo.note": "Title, description, social image",
  "pl.publish.check.analytics.label": "Analytics & tracking",
  "pl.publish.check.analytics.note": "Google Analytics connected",
  "pl.publish.linkTitle": "2- Your public link",
  "pl.publish.linkLive": "Your restaurant OS is live at this address.",
  "pl.publish.liveUrl": "Your live URL",
  "pl.publish.visitAsCustomer": "Visit as customer",
  "pl.publish.edit": "Edit",
  "pl.publish.address": "Public address",
  "pl.publish.addressHint": "Lowercase letters, numbers and hyphens, 3 to 63 characters.",
  "pl.publish.addressTaken": "This address is not available.",
  "pl.publish.domainTitle": "Custom Domain (Optional)",
  "pl.publish.domainNote": "Connect your own domain.",
  "pl.publish.domainField": "Domain",
  "pl.publish.domainConnect": "Connect",
  "pl.publish.domainChange": "Change",
  "pl.publish.sslNote": "Active (Auto-renew)",
  "pl.publish.sslActive": "Active",
  "pl.publish.sslPending": "Issued automatically once a domain is connected",
  "pl.publish.shareTitle": "Share your link",
  "pl.publish.shareNote": "Share your site everywhere.",
  "pl.publish.shareWith": "Share with",
  "pl.publish.addToSite": "Add to your site",
  "pl.publish.seoTitle": "SEO & Social",
  "pl.publish.seoNote": "Optimize how your site appears online.",
  "pl.publish.metaPlaceholder": "Enter your site meta description",
  "pl.publish.imageTypes": "PNG, JPG or WebP",
  // <pl-redesign:publish-en>
  "publicLink.checklist.address.label": "Public address claimed",
  "publicLink.checklist.address.note": "Choose your link in the Brand step",
  "pl.sync.dismiss": "Dismiss",
  "pl.sync.loading": "Loading your site…",
  "pl.sync.saving": "Saving…",
  "pl.common.save": "Save",
  "pl.common.saving": "Saving…",
  "pl.common.cancel": "Cancel",
  "pl.common.delete": "Delete",
  "pl.common.add": "Add",
  "pl.common.remove": "Remove",
  "pl.common.confirm": "Are you sure?",
  "pl.common.none": "None",
  "pl.theme.serverNote": "Themes set colours, fonts and layout. Your own colour and font choices are kept when you switch.",
  "pl.theme.applied": "Applied",
  "pl.theme.category.all": "All",
  "pl.starter.title": "Start from a ready-made site",
  "pl.starter.note": "Creates pages, navigation, footer and theme in one go. Available until your first publish; it replaces the pages you have now.",
  "pl.starter.recommended": "Recommended",
  "pl.starter.apply": "Apply",
  "pl.starter.confirm": "Replace your current pages, navigation, footer and theme with this starter?",
  "pl.starter.pages": "{n} pages",
  "pl.languages.title": "Site languages",
  "pl.languages.note": "Visitors can switch between enabled languages. Texts you type are saved in the default language.",
  "pl.languages.default": "Default",
  "pl.languages.enabled": "Enabled",
  "pl.brand.heroMoved": "The hero background is now set on the hero section itself (Customize step).",
  "pl.brand.resetting": "Resetting…",
  "pl.pages.title": "Title",
  "pl.pages.address": "Address",
  "pl.pages.visible": "Visible",
  "pl.pages.inNav": "In menu",
  "pl.pages.actions": "Actions",
  "pl.pages.add": "Add page",
  "pl.pages.addTitle": "Add a page",
  "pl.pages.templates": "From a template",
  "pl.pages.modules": "From your modules",
  "pl.pages.used": "Already on your site",
  "pl.pages.settings": "Page settings",
  "pl.pages.deleteConfirm": "Delete “{name}”? Its menu and footer links are removed too.",
  "pl.pages.home": "Home",
  "pl.pages.hidden": "Hidden",
  "pl.pages.previousPaths": "Old addresses (redirect here)",
  "pl.pages.seoTitle": "Search title",
  "pl.pages.seoDescription": "Search description",
  "pl.pages.noIndex": "Hide this page from search engines",
  "pl.pages.hideFooter": "Hide the footer on this page",
  "pl.pages.pathHint": "Lowercase letters, numbers and hyphens, e.g. about-us",
  "pl.pages.limit": "{used} of {max} pages",
  "pl.template.blank": "Blank page",
  "pl.template.home": "Home",
  "pl.template.about": "About us",
  "pl.template.contact": "Contact us",
  "pl.template.gallery": "Gallery",
  "pl.template.legal": "Terms & conditions",
  "pl.source.menu": "Menu",
  "pl.source.reservation": "Reservations",
  "pl.nav.items": "Menu items",
  "pl.nav.empty": "No menu items yet — your header lists every visible page in order.",
  "pl.nav.header": "Header",
  "pl.nav.drawer": "Drawer",
  "pl.nav.addPage": "Add a page to the menu",
  "pl.nav.addLink": "Add an outside link",
  "pl.nav.linkLabel": "Label",
  "pl.nav.linkUrl": "https://…",
  "pl.nav.warning": "Some menu items point at hidden pages.",
  "pl.footer.title": "Footer",
  "pl.footer.note": "Link groups, social profiles and contact details shown at the bottom of every page.",
  "pl.footer.group": "Group title",
  "pl.footer.addGroup": "Add link group",
  "pl.footer.social": "Social links",
  "pl.footer.addSocial": "Add social link",
  "pl.footer.contact": "Contact",
  "pl.footer.address": "Address",
  "pl.footer.hours": "Opening hours",
  "pl.footer.phone": "Phone",
  "pl.footer.saved": "Footer saved",
  "pl.sections.page": "Page",
  "pl.sections.empty": "This page has no sections yet.",
  "pl.sections.add": "Add section",
  "pl.sections.bound": "Connected content",
  "pl.sections.boundNote": "This section shows live content from another module. Edit the content there.",
  "pl.sections.unavailable": "Unavailable — it will reappear by itself once the content is available again.",
  "pl.sections.primary": "The main content of this page — it can't be removed or switched off.",
  "pl.sections.manage": "Manage content",
  "pl.sections.select": "Select a section to edit it.",
  "pl.sections.saved": "Section saved",
  "pl.sections.style": "Style",
  "pl.sections.variant": "Layout",
  "pl.sections.alignment": "Alignment",
  "pl.sections.align.start": "Start",
  "pl.sections.align.center": "Center",
  "pl.sections.align.end": "End",
  "pl.sections.hideOn": "Hide on",
  "pl.sections.device.mobile": "Mobile",
  "pl.sections.device.tablet": "Tablet",
  "pl.sections.device.desktop": "Desktop",
  "pl.sections.anchor": "Anchor (for in-page links)",
  "pl.sections.default": "Theme default",
  "pl.field.upload": "Upload",
  "pl.field.addItem": "Add item",
  "pl.field.item": "Item {n}",
  "pl.field.linkKind": "Link to",
  "pl.field.link.none": "No link",
  "pl.field.link.page": "A page",
  "pl.field.link.anchor": "A section",
  "pl.field.link.external": "A website",
  "pl.field.link.email": "Email",
  "pl.field.link.phone": "Phone",
  "pl.field.linkLabel": "Button text",
  "pl.field.newTab": "Open in a new tab",
  "pl.field.uploadFailed": "The image couldn't be uploaded. The previous one is kept.",
  "pl.preview.links": "Share a private preview",
  "pl.preview.linksNote": "Anyone with the link sees your latest draft — live, before you publish. Up to five links at a time.",
  "pl.preview.create": "Create preview link",
  "pl.preview.creating": "Creating…",
  "pl.preview.label": "Label (optional)",
  "pl.preview.newLink": "New link — copy it now, it is shown only once",
  "pl.preview.active": "Active links",
  "pl.preview.none": "No active preview links.",
  "pl.preview.expires": "Expires {date}",
  "pl.preview.revoke": "Revoke",
  "pl.preview.revokeAll": "Revoke all",
  "pl.preview.noPassword": "Password protection isn't available for preview links; links expire and can be revoked instead.",
  "pl.preview.createFirst": "Create a preview link to get a shareable address.",
  "pl.review.title": "Publishing review",
  "pl.review.refresh": "Check again",
  "pl.review.ok": "Nothing blocks publishing.",
  "pl.review.blocking": "Blocking",
  "pl.review.warnings": "Warnings",
  "pl.review.recommendations": "Suggestions",
  "pl.review.more": "+{n} more",
  "pl.seo.hideFromSearch": "Hide the whole site from search engines",
  "pl.seo.titleFormat": "Pages appear in search as “Page · {title}”.",
  "pl.publish.blockedTitle": "Publishing is blocked",
  "finding.publish.display-name-missing": "Your business name is missing in the default language.",
  "finding.publish.slug-missing": "No public address has been claimed yet.",
  "finding.site.invalid": "The site settings need attention.",
  "finding.page.invalid": "A page needs attention.",
  "finding.document.too-large": "The site is too large to publish.",
  "finding.source.settings-invalid": "Connected content has settings that are no longer valid.",
  "finding.source.unavailable": "Connected content is currently unavailable.",
  "finding.translation.missing": "A text is missing a translation.",
  "finding.link.dangling": "A link points at something that no longer exists.",
  "finding.link.target-hidden": "A link points at a hidden page or section.",
  "finding.navigation.item-not-shown": "A menu item is shown neither in the header nor in the drawer.",
  "finding.page.path-reserved": "A page uses a reserved address.",
  "finding.catalogue.drift": "Your theme or a section style is no longer offered; a default is used.",
  "finding.legacy.content-unmapped": "Some older content could not be carried over.",
  "finding.seo.description-missing": "Add a search description.",
  "finding.seo.social-image-small": "The social image is smaller than 1200×630.",
  "finding.page.no-content": "A page has no content.",
  "finding.page.unreachable": "A page can't be reached from the menu.",
  "pl.media.title": "Media library",
  "pl.media.library": "Library",
  "pl.media.manage": "Manage media library",
  "pl.media.note": "Files you uploaded for this site. Pick one to reuse it, or delete what you no longer need.",
  "pl.media.use": "Use this file",
  "pl.media.close": "Close",
  "pl.media.purpose": "Kind of file",
  "pl.media.purpose.all": "All files",
  "pl.media.purpose.Logo": "Logo",
  "pl.media.purpose.Favicon": "Favicon",
  "pl.media.purpose.HeroBackground": "Hero background",
  "pl.media.purpose.SectionImage": "Section image",
  "pl.media.purpose.SocialImage": "Social image",
  "pl.media.purpose.SectionVideo": "Section video",
  "pl.media.empty": "No files here yet. Upload one from any image field.",
  "pl.media.count": "{shown} of {total}",
  "pl.media.more": "Load more",
  "pl.media.deleteConfirm": "Delete this file from the library? This can't be undone.",
  "pl.media.inUse": "This file is still in use, so it can't be deleted. Remove it from these places first:",
  "pl.media.usedPage": "Page “{page}” (draft)",
  "pl.media.usedSite": "Site settings — {field} (draft)",
  "pl.media.usedVersions": "Published versions {versions} (kept for rollback)",
  "pl.rich.block": "Text style",
  "pl.rich.paragraph": "Paragraph",
  "pl.rich.h2": "Heading",
  "pl.rich.h3": "Subheading",
  "pl.rich.h4": "Small heading",
  "pl.rich.quote": "Quote",
  "pl.rich.bold": "Bold",
  "pl.rich.italic": "Italic",
  "pl.rich.underline": "Underline",
  "pl.rich.bullets": "Bulleted list",
  "pl.rich.numbers": "Numbered list",
  "pl.rich.indent": "Nest list item",
  "pl.rich.outdent": "Un-nest list item",
  "pl.rich.link": "Add or edit link",
  "pl.rich.unlink": "Remove link",
  "pl.rich.applyLink": "Apply link",
  "pl.rich.linkText": "link",
  "pl.rich.noAnchors": "No section on that page has an anchor yet. Give one an anchor (Style ▸ Anchor) to link to it.",
  "pl.rich.tooBig": "This text is too long to save (more than {max} elements). Shorten it or split it across sections.",
  "pl.settings.title": "Display settings",
  "pl.settings.note": "How this content is shown on your site. The module that owns the content checks them when you save.",
  "pl.settings.noSchema": "This module doesn't describe its settings yet. Add any setting it supports below; it checks them when you save.",
  "pl.settings.none": "No display settings — the module's defaults are used.",
  "pl.settings.raw": "Settings (JSON)",
  "pl.settings.badJson": "That isn't valid JSON.",
  "pl.settings.key": "Setting name",
  "pl.settings.type": "Type",
  "pl.settings.type.text": "Text",
  "pl.settings.type.number": "Number",
  "pl.settings.type.toggle": "On / off",
  "pl.settings.type.json": "JSON",
  "pl.settings.add": "Add setting",
  "pl.settings.unsaved": "Unsaved changes",
  "pl.module.unavailable": "Unavailable",
  "pl.module.shown": "Show on the site",
  "pl.module.shownNote": "Turn off to keep the section without showing it.",
  "pl.module.connectedTo": "Shows",
  "pl.module.primaryBinding": "This page was created for this content; create another page to show something else.",
  "pl.module.notListed": "This content isn't in your list any more (deleted, or you can't see it).",
  "pl.module.entries": "{n} entries",
  "pl.module.updated": "Updated {date}",
  "pl.module.hasPage": "Also has its own page",
  "pl.module.otherSections": "Also shown in {n} other section(s)",
  "pl.nav.group": "Group (no link, holds sub-items)",
  "pl.nav.addGroup": "Add a group",
  "pl.nav.addItemTitle": "New menu item",
  "pl.nav.editItem": "Edit menu item",
  "pl.nav.children": "Sub-items",
  "pl.nav.childrenCount": "{n} of {max}",
  "pl.nav.noChildren": "No sub-items. Add some to show a dropdown under this item.",
  "pl.nav.groupNeedsChildren": "A group needs at least one sub-item.",
  "pl.nav.addChildPage": "Add a page as a sub-item",
  "pl.nav.promote": "Move to the top level",
  "pl.nav.putUnder": "Place under",
  "pl.nav.topLevel": "Top level (no parent)",
  "pl.nav.childrenHint": "Items can hold up to {max} sub-items, one level deep. Use the pencil to edit them.",
  "pl.navp.too-many-items": "The menu can have at most {max} top-level items.",
  "pl.navp.too-many-children": "An item can have at most {max} sub-items.",
  "pl.navp.too-deep": "Sub-items can't have sub-items of their own.",
  "pl.navp.target-required": "A group needs at least one sub-item (or choose what it links to).",
  "pl.navp.label-required": "Links to other websites need a label.",
  "pl.navp.too-long": "Labels can be at most {max} characters.",
  "pl.navp.url-invalid": "Website links must be a full https:// address.",
  "pl.preview.open": "Open",
  "pl.preview.hide": "Done",
  "pl.preview.onceNote": "For your security this address is shown only now. Create a new link if you lose it.",
  "pl.brand.resetConfirm": "Reset colours, fonts and section styles to the theme's defaults? Your custom changes will be lost.",
  "pl.pages.socialImage": "Social image",
  "pl.pages.socialImageHint": "Shown when this page is shared. Leave empty to use the site's social image. Recommended 1200×630 px.",
};

const AR: Table = {
  "pl.v.required": "هذا الحقل مطلوب.",
  "pl.v.minLength": "أدخل {min} أحرف على الأقل.",
  "pl.v.maxLength": "الحد الأقصى {max} حرفًا.",
  "pl.v.email": "أدخل بريدًا إلكترونيًا صحيحًا، مثل name@example.com.",
  "pl.v.hexColor": "أدخل لونًا سداسيًا من 6 خانات، مثل ‎#08589D.",
  "pl.v.slug": "استخدم أحرفًا إنجليزية صغيرة وأرقامًا وشرطات فقط.",
  "pl.v.hostname": "أدخل نطاقًا صحيحًا، مثل www.example.com.",
  "pl.v.url": "أدخل عنوانًا كاملًا يبدأ بـ https://.",
  "pl.v.integer": "أدخل رقمًا صحيحًا.",
  "pl.v.amount": "أدخل مبلغًا صحيحًا، مثل 25 أو 25.50.",
  "pl.v.min": "يجب أن تكون القيمة {min} أو أكثر.",
  "pl.v.max": "يجب أن تكون القيمة {max} أو أقل.",
  "pl.v.rangeOrder": "يجب أن يكون الحد الأقصى أكبر من أو يساوي الحد الأدنى.",
  "pl.v.fileType": "نوع الملف غير مدعوم. استخدم {types}.",
  "pl.v.fileSize": "حجم الملف كبير. الحد الأقصى {max} ميجابايت.",
  "pl.v.duplicate": "هذه القيمة مضافة بالفعل.",
  "pl.v.fixBeforeNext": "صحّح الحقول المحددة قبل المتابعة.",
  "pl.shell.back": "رجوع",
  "pl.theme.allThemes": "كل القوالب",
  // <pl-redesign:theme-ar>
  "pl.brand.logoHintFormat": "الموصى به: PNG/SVG",
  "pl.brand.logoHintSize": "المقاس: 512×512 بكسل",
  "pl.brand.noLogo": "لا يوجد شعار بعد",
  "pl.brand.typographyEn": "الخطوط (الإنجليزية)",
  "pl.brand.typographyAr": "الخطوط (العربية)",
  "pl.brand.heroPattern": "نقش/خلفية الواجهة",
  // <pl-redesign:brand-ar>
  "pl.pages.reorderHint": "اسحب لإعادة ترتيب الصفحات في قائمة التنقل",
  "pl.pages.socialImageType": "PNG أو JPG أو WebP",
  // <pl-redesign:pages-ar>
  "pl.navigation.showInHeader": "إظهار في التنقل الرئيسي (الرأس)",
  "pl.navigation.showInDrawer": "إظهار في قائمة الجوال الجانبية",
  "pl.navigation.stickyHeaderNote": "إبقاء التنقل ظاهرًا أثناء التمرير",
  "pl.navigation.activeIndicator": "مؤشر الصفحة النشطة",
  "pl.navigation.activeIndicatorNote": "إبراز الصفحة الحالية في التنقل",
  "pl.navigation.showIcons": "إظهار الأيقونات في التنقل",
  "pl.navigation.showIconsNote": "عرض الأيقونات بجانب عناصر القائمة",
  "pl.navigation.sameTab": "فتح الروابط في نفس التبويب",
  "pl.navigation.sameTabNote": "السلوك الافتراضي لروابط القائمة",
  "pl.navigation.dragHint": "اسحب لإعادة ترتيب الصفحات في التنقل",
  "pl.navigation.tip": "نصيحة: يمكنك تغيير ترتيب الصفحات في التنقل",
  "pl.navigation.updatesInstantly": "يتحدّث التنقل فورًا عند إعادة الترتيب أو تغيير الظهور.",
  "pl.navigation.url": "عنوان الموقع",
  "pl.navigation.phoneInvalid": "أدخل رقم هاتف صحيحًا.",
  // <pl-redesign:navigation-ar>
  "pl.customize.insp.enterNumber": "أدخل رقمًا",
  "pl.customize.insp.min": "الأدنى",
  "pl.customize.insp.max": "الأقصى",
  "pl.customize.insp.partySize": "الحد الأدنى / الأقصى لعدد الأشخاص",
  "pl.customize.insp.displayOnHomepage": "طريقة العرض في الصفحة الرئيسية",
  "pl.customize.insp.primaryAction": "الإجراء الرئيسي لزر الدعوة",
  "pl.customize.insp.moduleSetting": "إعدادات الوحدة",
  "pl.customize.insp.widget": "ودجت الحجز",
  "pl.customize.insp.widgetNote": "نموذج حجز مضمّن.",
  "pl.customize.insp.button": "زر / رابط",
  "pl.customize.insp.buttonNote": "زر دعوة يفتح الحجز",
  "pl.customize.insp.availability": "معاينة التوفر",
  "pl.customize.insp.nextAvailable": "عرض أقرب وقت متاح",
  "pl.customize.insp.label": "التسمية",
  "pl.customize.insp.labelPlaceholder": "أدخل اسم التسمية",
  "pl.customize.insp.targetNote": "ينتقل الضيوف إلى هذه الصفحة",
  "pl.customize.insp.whatsapp": "إشعار واتساب",
  "pl.customize.insp.sms": "إشعار الرسائل النصية",
  "pl.customize.insp.email": "إشعار البريد الإلكتروني",
  "pl.customize.insp.optional": "(اختياري)",
  "pl.customize.menu.connect": "ربط قائمة محفوظة",
  "pl.customize.menu.connectNote": "اختر قائمة أنشأتها مسبقًا في وحدة القوائم.",
  "pl.customize.menu.select": "اختر القائمة",
  "pl.customize.menu.meta": "حُدّثت منذ {days} يوم. {items} صنف",
  "pl.customize.menu.displayNote": "اختر كيف تظهر قائمتك في الصفحة الرئيسية.",
  "pl.customize.menu.highlighted": "الأطباق المميزة",
  "pl.customize.menu.highlightedNote": "عرض أطباق شائعة مختارة",
  "pl.customize.menu.categories": "أقسام القائمة",
  "pl.customize.menu.categoriesNote": "عرض أقسام القائمة",
  "pl.customize.menu.preview": "معاينة القائمة",
  "pl.customize.menu.previewNote": "عرض معاينة للقائمة مع رابط",
  "pl.customize.menu.full": "القائمة كاملة",
  "pl.customize.menu.fullNote": "عرض القائمة كاملة في الصفحة الرئيسية",
  "pl.customize.menu.primaryNote": "اختر إلى أين ينقل زر القائمة الرئيسي العملاء.",
  "pl.customize.menu.openPage": "فتح صفحة القائمة",
  "pl.customize.menu.openPageNote": "فتح صفحة القائمة الكاملة في الموقع.",
  "pl.customize.menu.openDrawer": "فتح درج القائمة",
  "pl.customize.menu.openDrawerNote": "فتح القائمة في درج جانبي",
  "pl.customize.menu.openOrdering": "فتح الطلب / الحجوزات",
  "pl.customize.menu.openOrderingNote": "الانتقال مباشرة إلى الطلب أو الحجوزات.",
  "pl.customize.menu.moduleSetting": "إعدادات وحدة القائمة والطلب",
  "pl.customize.menu.moduleSettingNote": "اضبط سلوك الطلب والتوفر.",
  "pl.customize.menu.orderingMode": "وضع الطلب",
  "pl.customize.menu.modeOrdering": "طلب",
  "pl.customize.menu.modeReservation": "حجز",
  "pl.customize.menu.modeView": "عرض",
  "pl.customize.menu.minOrder": "الحد الأدنى للطلب",
  "pl.customize.menu.minOrderUnit": "(ر.س)",
  "pl.customize.menu.enterPrice": "أدخل السعر",
  "pl.customize.menu.orderAhead": "الطلب المسبق",
  "pl.customize.menu.orderAheadNote": "السماح للعملاء بتقديم طلبات لوقت لاحق",
  "pl.customize.menu.prepTime": "وقت التحضير المتوقع",
  "pl.customize.menu.prepTimePlaceholder": "أدخل الوقت المتوقع",
  "pl.customize.menu.prepTimeNote": "يظهر للعملاء عند إتمام الطلب.",
  "pl.customize.menu.serviceAreas": "مناطق الخدمة",
  "pl.customize.menu.serviceAreasUnit": "(التوصيل)",
  "pl.customize.menu.serviceAreasPlaceholder": "جدة، السلامة، الروضة",
  "pl.customize.menu.taxDisplay": "عرض الضريبة",
  "pl.customize.menu.taxInclusive": "عرض الأسعار شاملة ضريبة القيمة المضافة",
  "pl.customize.menu.taxExclusive": "عرض الأسعار غير شاملة ضريبة القيمة المضافة",
  "pl.customize.menu.taxNote": "طريقة عرض الأسعار للعملاء.",
  "pl.customize.res.module": "وحدة الحجوزات",
  "pl.customize.res.moduleNote": "فعّل واضبط الحجوزات لمطعمك.",
  "pl.customize.res.enable": "تفعيل الحجز",
  "pl.customize.res.enableNote": "السماح للمستخدمين بحجز الطاولات عبر الإنترنت.",
  "pl.customize.res.active": "وحدة الحجوزات مفعّلة.",
  "pl.customize.res.displayNote": "اختر كيف تظهر الحجوزات في الصفحة الرئيسية.",
  "pl.customize.res.primaryNote": "اختر الإجراء الرئيسي للحجز",
  "pl.customize.res.openForm": "فتح نموذج الحجز",
  "pl.customize.res.openFormNote": "يحجز الضيوف مباشرة من الصفحة الرئيسية",
  "pl.customize.res.availabilityNote": "عرض حالة التوفر في الصفحة الرئيسية.",
  "pl.customize.res.dateRange": "نطاق التواريخ للتحقق",
  "pl.customize.res.bookingWindow": "السماح بالحجز حتى",
  "pl.customize.res.cutOff": "وقت إغلاق الحجز",
  "pl.customize.res.tableHold": "مدة حجز الطاولة",
  "pl.customize.res.autoConfirm": "تأكيد تلقائي",
  "pl.customize.res.autoConfirmNote": "تأكيد الحجوزات تلقائيًا. عند التعطيل تلزم الموافقة.",
  "pl.customize.res.deposit": "عربون",
  "pl.customize.res.depositNote": "طلب عربون عند الحجز",
  "pl.customize.wl.module": "وحدة قائمة الانتظار",
  "pl.customize.wl.moduleNote": "فعّل واضبط قائمة الانتظار لمطعمك.",
  "pl.customize.wl.enable": "تفعيل قائمة الانتظار",
  "pl.customize.wl.enableNote": "يمكن للضيوف الانضمام إلى قائمة الانتظار عبر الإنترنت.",
  "pl.customize.wl.active": "وحدة قائمة الانتظار مفعّلة.",
  "pl.customize.wl.primaryNote": "اختر الإجراء الرئيسي لقائمة الانتظار",
  "pl.customize.wl.openDrawer": "فتح درج قائمة الانتظار",
  "pl.customize.wl.openDrawerNote": "ينضم الضيوف إلى قائمة الانتظار من درج جانبي",
  "pl.customize.wl.availabilityNote": "عرض وقت الانتظار المتوقع في الصفحة الرئيسية",
  "pl.customize.wl.format": "الصيغة",
  "pl.customize.wl.format.30min": "30 د",
  "pl.customize.wl.format.1h": "1 س",
  "pl.customize.wl.queueMethod": "طريقة الطابور",
  "pl.customize.wl.fifo": "الأسبقية لمن يأتي أولًا",
  "pl.customize.wl.fifoNote": "يُضاف الضيوف بالترتيب",
  "pl.customize.wl.priority": "قواعد الأولوية",
  "pl.customize.wl.priorityNote": "كبار الضيوف والحجوزات والحالات أولًا",
  "pl.customize.wl.waitTime": "عرض وقت الانتظار",
  "pl.customize.wl.waitTimeNote": "عرض وقت الانتظار المتوقع",
  "pl.customize.wl.updateInterval": "فترة التحديث",
  "pl.customize.wl.notifications": "الإشعارات",
  "pl.customize.wl.autoRemove": "الإزالة التلقائية",
  "pl.customize.wl.autoRemoveNote": "الإزالة إذا لم يؤكَّد خلال",
  "pl.customize.hero.headingPlaceholder": "أدخل العنوان",
  "pl.customize.hero.subheadingPlaceholder": "أدخل العنوان الفرعي",
  "pl.customize.hero.primaryCtaPlaceholder": "أدخل اسم الزر الأساسي",
  "pl.customize.hero.secondaryCtaPlaceholder": "أدخل اسم الزر الثانوي",
  "pl.customize.hero.imageTypes": "PNG أو JPG أو WebP",
  "pl.customize.hero.chooseAction": "اختر رابطًا أو إجراءً لهذا الزر.",
  "pl.customize.noImage": "لا توجد صورة بعد",
  "pl.customize.fixFields": "صحّح الحقول المحددة قبل الحفظ.",
  "pl.customize.settingKeyInvalid": "ابدأ بحرف، واستخدم الأحرف الإنجليزية والأرقام والشرطات والنقاط فقط.",
  // <pl-redesign:customize-ar>
  "pl.preview.testModeOff": "وضع الاختبار متوقف",
  "pl.preview.allCompleted": "اكتملت جميع الخطوات بنجاح.",
  "pl.preview.urlLabel": "رابط المعاينة",
  "pl.preview.urlMode": "(وضع الاختبار)",
  "pl.preview.inviteNote": "شارك المعاينة مع فريقك أو عملائك.",
  "pl.preview.emailPlaceholder": "أدخل البريد الإلكتروني",
  "pl.preview.canViewTest": "يمكنه عرض الاختبار",
  "pl.preview.testers": "المختبرون",
  "pl.preview.labelField": "تسمية الرابط",
  "pl.preview.optional": "(اختياري)",
  "pl.preview.labelPlaceholder": "مثال: لفريق التصميم",
  // <pl-redesign:preview-ar>
  "pl.publish.checklistTitle": "1- قائمة الجاهزية للنشر",
  "pl.publish.checklistReady": "كل شيء يبدو جيدًا، موقعك جاهز للنشر.",
  "pl.publish.checklistPending": "أكمل العناصر التي تحمل زر «إصلاح» ثم انشر.",
  "pl.publish.check.pages.label": "جميع الصفحات منشورة",
  "pl.publish.check.pages.note": "{n} صفحات",
  "pl.publish.check.navigation.label": "التنقل مضبوط",
  "pl.publish.check.navigation.note": "جميع عناصر القائمة مرتبطة",
  "pl.publish.check.menu.label": "المنيو مرتبط",
  "pl.publish.check.menu.note": "جميع عناصر المنيو مرتبطة",
  "pl.publish.check.reservations.label": "الحجز يعمل",
  "pl.publish.check.reservations.note": "مسار الحجز مفعّل",
  "pl.publish.check.waitlist.label": "قائمة الانتظار تعمل",
  "pl.publish.check.waitlist.note": "الانضمام والإشعارات مفعّلة",
  "pl.publish.check.payments.label": "المدفوعات مهيأة",
  "pl.publish.check.payments.note": "ميسّر (وضع الاختبار)",
  "pl.publish.check.responsive.label": "متجاوب ويدعم العربية",
  "pl.publish.check.responsive.note": "سطح المكتب، التابلت، الجوال، RTL",
  "pl.publish.check.seo.label": "إعدادات SEO الأساسية",
  "pl.publish.check.seo.note": "العنوان، الوصف، صورة المشاركة",
  "pl.publish.check.analytics.label": "التحليلات والتتبع",
  "pl.publish.check.analytics.note": "Google Analytics مرتبط",
  "pl.publish.linkTitle": "2- رابطك العام",
  "pl.publish.linkLive": "موقع مطعمك متاح الآن على هذا العنوان.",
  "pl.publish.liveUrl": "رابط موقعك",
  "pl.publish.visitAsCustomer": "زيارة كعميل",
  "pl.publish.edit": "تعديل",
  "pl.publish.address": "العنوان العام",
  "pl.publish.addressHint": "أحرف إنجليزية صغيرة وأرقام وشرطات، من 3 إلى 63 حرفًا.",
  "pl.publish.addressTaken": "هذا العنوان غير متاح.",
  "pl.publish.domainTitle": "نطاق مخصص (اختياري)",
  "pl.publish.domainNote": "اربط نطاقك الخاص.",
  "pl.publish.domainField": "النطاق",
  "pl.publish.domainConnect": "ربط",
  "pl.publish.domainChange": "تغيير",
  "pl.publish.sslNote": "نشطة (تجديد تلقائي)",
  "pl.publish.sslActive": "نشطة",
  "pl.publish.sslPending": "تصدر تلقائيًا بعد ربط النطاق",
  "pl.publish.shareTitle": "شارك رابطك",
  "pl.publish.shareNote": "شارك موقعك في كل مكان.",
  "pl.publish.shareWith": "شارك مع",
  "pl.publish.addToSite": "أضفه إلى موقعك",
  "pl.publish.seoTitle": "SEO والمشاركة",
  "pl.publish.seoNote": "حسّن ظهور موقعك على الإنترنت.",
  "pl.publish.metaPlaceholder": "أدخل وصف الموقع",
  "pl.publish.imageTypes": "PNG أو JPG أو WebP",
  // <pl-redesign:publish-ar>
  "publicLink.checklist.address.label": "تم حجز العنوان العام",
  "publicLink.checklist.address.note": "اختر رابطك في خطوة الهوية",
  "pl.sync.dismiss": "إغلاق",
  "pl.sync.loading": "جارٍ تحميل موقعك…",
  "pl.sync.saving": "جارٍ الحفظ…",
  "pl.common.save": "حفظ",
  "pl.common.saving": "جارٍ الحفظ…",
  "pl.common.cancel": "إلغاء",
  "pl.common.delete": "حذف",
  "pl.common.add": "إضافة",
  "pl.common.remove": "إزالة",
  "pl.common.confirm": "هل أنت متأكد؟",
  "pl.common.none": "لا شيء",
  "pl.theme.serverNote": "تحدد القوالب الألوان والخطوط والتخطيط. تبقى اختياراتك الخاصة للألوان والخطوط عند التبديل.",
  "pl.theme.applied": "مطبّق",
  "pl.theme.category.all": "الكل",
  "pl.starter.title": "ابدأ من موقع جاهز",
  "pl.starter.note": "ينشئ الصفحات والقائمة والتذييل والقالب دفعة واحدة. متاح حتى أول نشر، ويستبدل صفحاتك الحالية.",
  "pl.starter.recommended": "موصى به",
  "pl.starter.apply": "تطبيق",
  "pl.starter.confirm": "استبدال صفحاتك وقائمتك وتذييلك وقالبك الحالي بهذا الموقع الجاهز؟",
  "pl.starter.pages": "{n} صفحات",
  "pl.languages.title": "لغات الموقع",
  "pl.languages.note": "يمكن للزوار التبديل بين اللغات المفعّلة. تُحفظ النصوص التي تكتبها باللغة الافتراضية.",
  "pl.languages.default": "الافتراضية",
  "pl.languages.enabled": "مفعّلة",
  "pl.brand.heroMoved": "تُضبط خلفية الواجهة الآن من قسم الواجهة نفسه (خطوة التخصيص).",
  "pl.brand.resetting": "جارٍ الاستعادة…",
  "pl.pages.title": "العنوان",
  "pl.pages.address": "الرابط",
  "pl.pages.visible": "ظاهرة",
  "pl.pages.inNav": "في القائمة",
  "pl.pages.actions": "إجراءات",
  "pl.pages.add": "إضافة صفحة",
  "pl.pages.addTitle": "إضافة صفحة",
  "pl.pages.templates": "من قالب",
  "pl.pages.modules": "من وحداتك",
  "pl.pages.used": "موجودة في موقعك",
  "pl.pages.settings": "إعدادات الصفحة",
  "pl.pages.deleteConfirm": "حذف «{name}»؟ ستُزال روابطها من القائمة والتذييل أيضًا.",
  "pl.pages.home": "الرئيسية",
  "pl.pages.hidden": "مخفية",
  "pl.pages.previousPaths": "عناوين قديمة (تُحوَّل إلى هنا)",
  "pl.pages.seoTitle": "عنوان البحث",
  "pl.pages.seoDescription": "وصف البحث",
  "pl.pages.noIndex": "إخفاء هذه الصفحة عن محركات البحث",
  "pl.pages.hideFooter": "إخفاء التذييل في هذه الصفحة",
  "pl.pages.pathHint": "أحرف إنجليزية صغيرة وأرقام وشرطات، مثل about-us",
  "pl.pages.limit": "{used} من {max} صفحات",
  "pl.template.blank": "صفحة فارغة",
  "pl.template.home": "الرئيسية",
  "pl.template.about": "من نحن",
  "pl.template.contact": "تواصل معنا",
  "pl.template.gallery": "المعرض",
  "pl.template.legal": "الشروط والأحكام",
  "pl.source.menu": "المنيو",
  "pl.source.reservation": "الحجوزات",
  "pl.nav.items": "عناصر القائمة",
  "pl.nav.empty": "لا توجد عناصر بعد — يعرض الشريط العلوي كل الصفحات الظاهرة بالترتيب.",
  "pl.nav.header": "الشريط العلوي",
  "pl.nav.drawer": "القائمة الجانبية",
  "pl.nav.addPage": "إضافة صفحة إلى القائمة",
  "pl.nav.addLink": "إضافة رابط خارجي",
  "pl.nav.linkLabel": "النص",
  "pl.nav.linkUrl": "https://…",
  "pl.nav.warning": "بعض عناصر القائمة تشير إلى صفحات مخفية.",
  "pl.footer.title": "التذييل",
  "pl.footer.note": "مجموعات روابط وحسابات التواصل وبيانات الاتصال أسفل كل صفحة.",
  "pl.footer.group": "عنوان المجموعة",
  "pl.footer.addGroup": "إضافة مجموعة روابط",
  "pl.footer.social": "روابط التواصل الاجتماعي",
  "pl.footer.addSocial": "إضافة رابط تواصل",
  "pl.footer.contact": "التواصل",
  "pl.footer.address": "العنوان",
  "pl.footer.hours": "ساعات العمل",
  "pl.footer.phone": "الهاتف",
  "pl.footer.saved": "تم حفظ التذييل",
  "pl.sections.page": "الصفحة",
  "pl.sections.empty": "لا توجد أقسام في هذه الصفحة بعد.",
  "pl.sections.add": "إضافة قسم",
  "pl.sections.bound": "محتوى مرتبط",
  "pl.sections.boundNote": "يعرض هذا القسم محتوى مباشرًا من وحدة أخرى. عدّل المحتوى هناك.",
  "pl.sections.unavailable": "غير متاح — سيظهر تلقائيًا عند توفر المحتوى مرة أخرى.",
  "pl.sections.primary": "المحتوى الأساسي لهذه الصفحة — لا يمكن حذفه أو إيقافه.",
  "pl.sections.manage": "إدارة المحتوى",
  "pl.sections.select": "اختر قسمًا لتعديله.",
  "pl.sections.saved": "تم حفظ القسم",
  "pl.sections.style": "التنسيق",
  "pl.sections.variant": "التخطيط",
  "pl.sections.alignment": "المحاذاة",
  "pl.sections.align.start": "البداية",
  "pl.sections.align.center": "الوسط",
  "pl.sections.align.end": "النهاية",
  "pl.sections.hideOn": "إخفاء على",
  "pl.sections.device.mobile": "الجوال",
  "pl.sections.device.tablet": "الجهاز اللوحي",
  "pl.sections.device.desktop": "سطح المكتب",
  "pl.sections.anchor": "المعرّف (للروابط داخل الصفحة)",
  "pl.sections.default": "افتراضي القالب",
  "pl.field.upload": "رفع",
  "pl.field.addItem": "إضافة عنصر",
  "pl.field.item": "العنصر {n}",
  "pl.field.linkKind": "الرابط إلى",
  "pl.field.link.none": "بدون رابط",
  "pl.field.link.page": "صفحة",
  "pl.field.link.anchor": "قسم",
  "pl.field.link.external": "موقع خارجي",
  "pl.field.link.email": "بريد إلكتروني",
  "pl.field.link.phone": "هاتف",
  "pl.field.linkLabel": "نص الزر",
  "pl.field.newTab": "فتح في تبويب جديد",
  "pl.field.uploadFailed": "تعذّر رفع الصورة. تم الإبقاء على الصورة السابقة.",
  "pl.preview.links": "مشاركة معاينة خاصة",
  "pl.preview.linksNote": "كل من لديه الرابط يرى أحدث مسودة مباشرة قبل النشر. حتى خمسة روابط في الوقت نفسه.",
  "pl.preview.create": "إنشاء رابط معاينة",
  "pl.preview.creating": "جارٍ الإنشاء…",
  "pl.preview.label": "تسمية (اختياري)",
  "pl.preview.newLink": "رابط جديد — انسخه الآن، يظهر مرة واحدة فقط",
  "pl.preview.active": "الروابط النشطة",
  "pl.preview.none": "لا توجد روابط معاينة نشطة.",
  "pl.preview.expires": "ينتهي {date}",
  "pl.preview.revoke": "إلغاء",
  "pl.preview.revokeAll": "إلغاء الكل",
  "pl.preview.noPassword": "لا تدعم روابط المعاينة كلمات المرور؛ تنتهي صلاحيتها ويمكن إلغاؤها بدلًا من ذلك.",
  "pl.preview.createFirst": "أنشئ رابط معاينة للحصول على عنوان قابل للمشاركة.",
  "pl.review.title": "مراجعة النشر",
  "pl.review.refresh": "تحقق مجددًا",
  "pl.review.ok": "لا شيء يمنع النشر.",
  "pl.review.blocking": "مانع",
  "pl.review.warnings": "تنبيهات",
  "pl.review.recommendations": "اقتراحات",
  "pl.review.more": "+{n} أخرى",
  "pl.seo.hideFromSearch": "إخفاء الموقع بالكامل عن محركات البحث",
  "pl.seo.titleFormat": "تظهر الصفحات في البحث بصيغة «الصفحة · {title}».",
  "pl.publish.blockedTitle": "النشر متوقف",
  "finding.publish.display-name-missing": "اسم نشاطك غير موجود باللغة الافتراضية.",
  "finding.publish.slug-missing": "لم يتم حجز عنوان عام بعد.",
  "finding.site.invalid": "إعدادات الموقع تحتاج إلى مراجعة.",
  "finding.page.invalid": "هناك صفحة تحتاج إلى مراجعة.",
  "finding.document.too-large": "الموقع أكبر من الحد المسموح للنشر.",
  "finding.source.settings-invalid": "إعدادات محتوى مرتبط لم تعد صالحة.",
  "finding.source.unavailable": "محتوى مرتبط غير متاح حاليًا.",
  "finding.translation.missing": "هناك نص بدون ترجمة.",
  "finding.link.dangling": "رابط يشير إلى شيء لم يعد موجودًا.",
  "finding.link.target-hidden": "رابط يشير إلى صفحة أو قسم مخفي.",
  "finding.navigation.item-not-shown": "عنصر قائمة غير ظاهر في الشريط العلوي ولا في القائمة الجانبية.",
  "finding.page.path-reserved": "صفحة تستخدم عنوانًا محجوزًا.",
  "finding.catalogue.drift": "القالب أو تنسيق قسم لم يعد متاحًا؛ يُستخدم الافتراضي.",
  "finding.legacy.content-unmapped": "تعذّر نقل بعض المحتوى القديم.",
  "finding.seo.description-missing": "أضف وصفًا لمحركات البحث.",
  "finding.seo.social-image-small": "صورة المشاركة أصغر من 1200×630.",
  "finding.page.no-content": "صفحة بلا محتوى.",
  "finding.page.unreachable": "صفحة لا يمكن الوصول إليها من القائمة.",
  "pl.media.title": "مكتبة الوسائط",
  "pl.media.library": "المكتبة",
  "pl.media.manage": "إدارة مكتبة الوسائط",
  "pl.media.note": "الملفات التي رفعتها لهذا الموقع. اختر ملفًا لإعادة استخدامه، أو احذف ما لم تعد تحتاجه.",
  "pl.media.use": "استخدام هذا الملف",
  "pl.media.close": "إغلاق",
  "pl.media.purpose": "نوع الملف",
  "pl.media.purpose.all": "كل الملفات",
  "pl.media.purpose.Logo": "الشعار",
  "pl.media.purpose.Favicon": "أيقونة الموقع",
  "pl.media.purpose.HeroBackground": "خلفية الواجهة",
  "pl.media.purpose.SectionImage": "صورة قسم",
  "pl.media.purpose.SocialImage": "صورة المشاركة",
  "pl.media.purpose.SectionVideo": "فيديو قسم",
  "pl.media.empty": "لا توجد ملفات بعد. ارفع ملفًا من أي حقل صورة.",
  "pl.media.count": "{shown} من {total}",
  "pl.media.more": "تحميل المزيد",
  "pl.media.deleteConfirm": "حذف هذا الملف من المكتبة؟ لا يمكن التراجع عن ذلك.",
  "pl.media.inUse": "هذا الملف ما زال مستخدمًا ولا يمكن حذفه. أزله من هذه الأماكن أولًا:",
  "pl.media.usedPage": "صفحة «{page}» (المسودة)",
  "pl.media.usedSite": "إعدادات الموقع — {field} (المسودة)",
  "pl.media.usedVersions": "النسخ المنشورة {versions} (محفوظة للاسترجاع)",
  "pl.rich.block": "نمط النص",
  "pl.rich.paragraph": "فقرة",
  "pl.rich.h2": "عنوان",
  "pl.rich.h3": "عنوان فرعي",
  "pl.rich.h4": "عنوان صغير",
  "pl.rich.quote": "اقتباس",
  "pl.rich.bold": "عريض",
  "pl.rich.italic": "مائل",
  "pl.rich.underline": "تسطير",
  "pl.rich.bullets": "قائمة نقطية",
  "pl.rich.numbers": "قائمة مرقمة",
  "pl.rich.indent": "إزاحة عنصر القائمة للداخل",
  "pl.rich.outdent": "إزاحة عنصر القائمة للخارج",
  "pl.rich.link": "إضافة رابط أو تعديله",
  "pl.rich.unlink": "إزالة الرابط",
  "pl.rich.applyLink": "تطبيق الرابط",
  "pl.rich.linkText": "رابط",
  "pl.rich.noAnchors": "لا يوجد قسم في تلك الصفحة له معرّف بعد. أضف معرّفًا لقسم (التنسيق ▸ المعرّف) للربط به.",
  "pl.rich.tooBig": "هذا النص أطول من أن يُحفظ (أكثر من {max} عنصر). اختصره أو وزّعه على عدة أقسام.",
  "pl.settings.title": "إعدادات العرض",
  "pl.settings.note": "طريقة عرض هذا المحتوى في موقعك. تتحقق منها الوحدة المالكة للمحتوى عند الحفظ.",
  "pl.settings.noSchema": "هذه الوحدة لا تصف إعداداتها بعد. أضف أي إعداد تدعمه أدناه؛ ستتحقق منه عند الحفظ.",
  "pl.settings.none": "لا توجد إعدادات عرض — تُستخدم الإعدادات الافتراضية للوحدة.",
  "pl.settings.raw": "الإعدادات (JSON)",
  "pl.settings.badJson": "هذا ليس JSON صالحًا.",
  "pl.settings.key": "اسم الإعداد",
  "pl.settings.type": "النوع",
  "pl.settings.type.text": "نص",
  "pl.settings.type.number": "رقم",
  "pl.settings.type.toggle": "تشغيل / إيقاف",
  "pl.settings.type.json": "JSON",
  "pl.settings.add": "إضافة إعداد",
  "pl.settings.unsaved": "تغييرات غير محفوظة",
  "pl.module.unavailable": "غير متاح",
  "pl.module.shown": "إظهار في الموقع",
  "pl.module.shownNote": "أوقفه للإبقاء على القسم دون عرضه.",
  "pl.module.connectedTo": "يعرض",
  "pl.module.primaryBinding": "أُنشئت هذه الصفحة لهذا المحتوى؛ أنشئ صفحة أخرى لعرض محتوى مختلف.",
  "pl.module.notListed": "هذا المحتوى لم يعد في قائمتك (حُذف، أو لا تملك صلاحية رؤيته).",
  "pl.module.entries": "{n} عنصر",
  "pl.module.updated": "آخر تحديث {date}",
  "pl.module.hasPage": "له صفحة خاصة أيضًا",
  "pl.module.otherSections": "معروض أيضًا في {n} قسم آخر",
  "pl.nav.group": "مجموعة (بدون رابط، تضم عناصر فرعية)",
  "pl.nav.addGroup": "إضافة مجموعة",
  "pl.nav.addItemTitle": "عنصر قائمة جديد",
  "pl.nav.editItem": "تعديل عنصر القائمة",
  "pl.nav.children": "العناصر الفرعية",
  "pl.nav.childrenCount": "{n} من {max}",
  "pl.nav.noChildren": "لا توجد عناصر فرعية. أضف بعضها لعرض قائمة منسدلة تحت هذا العنصر.",
  "pl.nav.groupNeedsChildren": "المجموعة تحتاج إلى عنصر فرعي واحد على الأقل.",
  "pl.nav.addChildPage": "إضافة صفحة كعنصر فرعي",
  "pl.nav.promote": "نقل إلى المستوى الأعلى",
  "pl.nav.putUnder": "وضعه تحت",
  "pl.nav.topLevel": "المستوى الأعلى (بدون أصل)",
  "pl.nav.childrenHint": "يمكن لكل عنصر أن يضم حتى {max} عناصر فرعية بمستوى واحد. استخدم القلم لتعديلها.",
  "pl.navp.too-many-items": "يمكن أن تضم القائمة {max} عناصر رئيسية على الأكثر.",
  "pl.navp.too-many-children": "يمكن أن يضم العنصر {max} عناصر فرعية على الأكثر.",
  "pl.navp.too-deep": "لا يمكن أن تحتوي العناصر الفرعية على عناصر فرعية.",
  "pl.navp.target-required": "المجموعة تحتاج إلى عنصر فرعي واحد على الأقل (أو اختر وجهة للرابط).",
  "pl.navp.label-required": "روابط المواقع الأخرى تحتاج إلى نص.",
  "pl.navp.too-long": "يمكن أن يكون النص {max} حرفًا على الأكثر.",
  "pl.navp.url-invalid": "يجب أن تكون روابط المواقع عنوانًا كاملًا يبدأ بـ https://.",
  "pl.preview.open": "فتح",
  "pl.preview.hide": "تم",
  "pl.preview.onceNote": "لأمانك يظهر هذا العنوان الآن فقط. أنشئ رابطًا جديدًا إذا فقدته.",
  "pl.brand.resetConfirm": "إعادة الألوان والخطوط وأنماط الأقسام إلى إعدادات القالب؟ ستفقد تعديلاتك الخاصة.",
  "pl.pages.socialImage": "صورة المشاركة",
  "pl.pages.socialImageHint": "تظهر عند مشاركة هذه الصفحة. اتركها فارغة لاستخدام صورة الموقع. المقاس الموصى به 1200×630 بكسل.",
};

/** Turns a catalogue label key ("sections.hero.fields.title") into readable text:
 *  the translated label when known, else a humanized form ("Title"). */
export function humanizeKey(key: string, locale?: string): string {
  const known = catalogueText(key, locale);
  if (known) return known;
  const last = key.split(".").pop() ?? key;
  const words = last.replace(/([a-z])([A-Z])/g, "$1 $2").replace(/[-_]+/g, " ").trim();
  return words ? words.charAt(0).toUpperCase() + words.slice(1) : key;
}

export function usePlText() {
  const { t, locale } = useI18n();
  return useCallback(
    (key: string, vars?: Record<string, string | number>) => {
      const own = t(key);
      let text = own !== key ? own : (locale === "ar" ? AR : EN)[key] ?? EN[key] ?? key;
      if (vars) for (const [k, v] of Object.entries(vars)) text = text.replace(`{${k}}`, String(v));
      return text;
    },
    [t, locale]
  );
}

/** A review finding's human text; unknown codes fall back to the code itself. */
export function findingText(tx: (key: string) => string, code: string): string {
  const key = `finding.${code}`;
  const text = tx(key);
  return text === key ? code : text;
}
