import { lazy, type LazyExoticComponent, type ComponentType } from "react";

export interface AppRoute {
  id: string; // matches the sidebar group id
  path: string; // react-router path
  section: string; // breadcrumb: left side
  page: string; // breadcrumb: right side
  element: LazyExoticComponent<ComponentType>;
}

export const routes: AppRoute[] = [
  { id: "dashboard",    path: "/",             section: "Dashboard",    page: "Overview",
    element: lazy(() => import("@/pages/dashboard").then(m => ({ default: m.DashboardPage }))) },
  { id: "orders",       path: "/orders",       section: "Orders",       page: "Live Orders",
    element: lazy(() => import("@/pages/orders-list").then(m => ({ default: m.OrdersListPage }))) },
  { id: "order-history", path: "/orders/history", section: "Orders", page: "Order History",
    element: lazy(() => import("@/pages/order-history").then(m => ({ default: m.OrderHistoryPage }))) },
  { id: "preorders",    path: "/orders/preorders", section: "Orders", page: "Pre-Orders & Scheduled",
    element: lazy(() => import("@/pages/preorders").then(m => ({ default: m.PreOrdersPage }))) },
  { id: "kds",          path: "/kds",          section: "Orders",       page: "Kitchen Display",
    element: lazy(() => import("@/pages/kds").then(m => ({ default: m.KdsPage }))) },
  { id: "reservations", path: "/reservations", section: "Reservations", page: "Reservations",
    element: lazy(() => import("@/pages/reservations").then(m => ({ default: m.ReservationsPage }))) },
  { id: "reservations-floor-plan", path: "/reservations/floor-plan", section: "Reservations", page: "Floor Plan",
    element: lazy(() => import("@/pages/reservations/floor-plan").then(m => ({ default: m.FloorPlanPage }))) },
  { id: "reservations-waitlist", path: "/reservations/waitlist", section: "Reservations", page: "Waitlist",
    element: lazy(() => import("@/pages/reservations/waitlist").then(m => ({ default: m.WaitlistPage }))) },
  { id: "menu",         path: "/menu",         section: "Menu",         page: "Menu",
    element: lazy(() => import("@/pages/menu/library").then(m => ({ default: m.MenuLibraryPage }))) },
  { id: "menu-items",   path: "/menu/items",   section: "Menu",         page: "Categories & Items",
    element: lazy(() => import("@/pages/menu/items").then(m => ({ default: m.MenuItemsPage }))) },
  { id: "menu-modifiers", path: "/menu/modifiers", section: "Menu",   page: "Modifiers",
    element: lazy(() => import("@/pages/menu/modifiers").then(m => ({ default: m.MenuModifiersPage }))) },
  { id: "menu-combos",  path: "/menu/combos",  section: "Menu",         page: "Combos",
    element: lazy(() => import("@/pages/menu/combos").then(m => ({ default: m.MenuCombosPage }))) },
  { id: "menu-pricing", path: "/menu/pricing", section: "Menu",         page: "Price Lists & Channels",
    element: lazy(() => import("@/pages/menu/pricing").then(m => ({ default: m.MenuPricingPage }))) },
  { id: "menu-schedules", path: "/menu/schedules", section: "Menu",   page: "Schedules & Ramadan Profile",
    element: lazy(() => import("@/pages/menu/schedules").then(m => ({ default: m.MenuSchedulesPage }))) },
  { id: "menu-availability", path: "/menu/availability", section: "Menu", page: "Availability (86 board)",
    element: lazy(() => import("@/pages/menu/availability").then(m => ({ default: m.MenuAvailabilityPage }))) },
  { id: "public-link", path: "/public-link", section: "Storefront", page: "Public Link Builder",
    element: lazy(() => import("@/pages/public-link").then(m => ({ default: m.PublicLinkBuilderPage }))) },
  { id: "inventory",    path: "/inventory",    section: "Inventory",    page: "Ingredients & Stock",
    element: lazy(() => import("@/pages/inventory").then(m => ({ default: m.InventoryPage }))) },
  { id: "inventory-ingredients", path: "/inventory/ingredients", section: "Inventory", page: "Ingredients & Suppliers",
    element: lazy(() => import("@/pages/inventory/ingredients").then(m => ({ default: m.IngredientsPage }))) },
  { id: "inventory-recipes", path: "/inventory/recipes", section: "Inventory", page: "Recipes & Costing",
    element: lazy(() => import("@/pages/inventory/recipes").then(m => ({ default: m.RecipesPage }))) },
  { id: "inventory-purchasing", path: "/inventory/purchasing", section: "Inventory", page: "Purchase Orders & Receipts",
    element: lazy(() => import("@/pages/inventory/purchasing").then(m => ({ default: m.PurchasingPage }))) },
  { id: "inventory-counts", path: "/inventory/counts", section: "Inventory", page: "Stock Counts & Variance",
    element: lazy(() => import("@/pages/inventory/counts").then(m => ({ default: m.CountsPage }))) },
  { id: "inventory-waste", path: "/inventory/waste", section: "Inventory", page: "Waste",
    element: lazy(() => import("@/pages/inventory/waste").then(m => ({ default: m.WastePage }))) },
  { id: "inventory-transfers", path: "/inventory/transfers", section: "Inventory", page: "Transfers",
    element: lazy(() => import("@/pages/inventory/transfers").then(m => ({ default: m.TransfersPage }))) },
  { id: "inventory-production", path: "/inventory/production", section: "Inventory", page: "Production",
    element: lazy(() => import("@/pages/inventory/production").then(m => ({ default: m.ProductionPage }))) },
  { id: "customers",    path: "/customers",    section: "Customers",    page: "Customer List",
    element: lazy(() => import("@/pages/customers").then(m => ({ default: m.CustomersPage }))) },
  { id: "customer-detail", path: "/customers/:id", section: "Customers", page: "Customer Profile",
    element: lazy(() => import("@/pages/customers/detail").then(m => ({ default: m.CustomerDetailPage }))) },
  { id: "customer-segments", path: "/customers/segments", section: "Customers", page: "Segments",
    element: lazy(() => import("@/pages/customers/segments").then(m => ({ default: m.CustomerSegmentsPage }))) },
  { id: "customer-segment-detail", path: "/customers/segments/:id", section: "Customers", page: "Segment Detail",
    element: lazy(() => import("@/pages/customers/segments/detail").then(m => ({ default: m.CustomerSegmentDetailPage }))) },
  { id: "customer-feedback", path: "/customers/feedback", section: "Customers", page: "Feedback & Complaints",
    element: lazy(() => import("@/pages/customers/feedback").then(m => ({ default: m.CustomerFeedbackPage }))) },
  { id: "customer-feedback-detail", path: "/customers/feedback/:id", section: "Customers", page: "Feedback Detail",
    element: lazy(() => import("@/pages/customers/feedback/detail").then(m => ({ default: m.CustomerFeedbackDetailPage }))) },
  { id: "marketing",    path: "/marketing",    section: "Marketing",    page: "Loyalty & Campaigns",
    element: lazy(() => import("@/pages/marketing").then(m => ({ default: m.MarketingPage }))) },
  { id: "marketing-loyalty", path: "/marketing/loyalty", section: "Marketing", page: "Loyalty Program",
    element: lazy(() => import("@/pages/marketing/loyalty").then(m => ({ default: m.LoyaltyProgramPage }))) },
  { id: "marketing-gift-cards", path: "/marketing/gift-cards", section: "Marketing", page: "Gift Cards",
    element: lazy(() => import("@/pages/marketing/gift-cards").then(m => ({ default: m.GiftCardsPage }))) },
  { id: "marketing-subscriptions", path: "/marketing/subscriptions", section: "Marketing", page: "Subscriptions & Memberships",
    element: lazy(() => import("@/pages/marketing/subscriptions").then(m => ({ default: m.SubscriptionsPage }))) },
  { id: "marketing-promotions", path: "/marketing/promotions", section: "Marketing", page: "Promotions & Vouchers",
    element: lazy(() => import("@/pages/marketing/promotions").then(m => ({ default: m.PromotionsPage }))) },
  { id: "marketing-campaigns", path: "/marketing/campaigns", section: "Marketing", page: "Campaigns",
    element: lazy(() => import("@/pages/marketing/campaigns").then(m => ({ default: m.CampaignsPage }))) },
  { id: "delivery-aggregators", path: "/delivery/aggregators", section: "Delivery", page: "Delivery Partners",
    element: lazy(() => import("@/pages/delivery/aggregators").then(m => ({ default: m.DeliveryAggregatorsPage }))) },
  { id: "finance",      path: "/finance",      section: "Finance",      page: "Payments & ZATCA",
    element: lazy(() => import("@/pages/finance").then(m => ({ default: m.FinancePage }))) },
  { id: "finance-payments", path: "/finance/payments", section: "Finance", page: "Payments & Transactions",
    element: lazy(() => import("@/pages/finance/payments").then(m => ({ default: m.PaymentsPage }))) },
  { id: "finance-tax-invoices", path: "/finance/tax-invoices", section: "Finance", page: "Tax Invoices (ZATCA)",
    element: lazy(() => import("@/pages/finance/tax-invoices").then(m => ({ default: m.TaxInvoicesPage }))) },
  { id: "finance-settlements", path: "/finance/settlements", section: "Finance", page: "Settlements & Reconciliation",
    element: lazy(() => import("@/pages/finance/settlements").then(m => ({ default: m.SettlementsPage }))) },
  { id: "finance-accounting", path: "/finance/accounting", section: "Finance", page: "Accounting Sync",
    element: lazy(() => import("@/pages/finance/accounting").then(m => ({ default: m.AccountingPage }))) },
  { id: "finance-house-accounts", path: "/finance/house-accounts", section: "Finance", page: "House Accounts",
    element: lazy(() => import("@/pages/finance/house-accounts").then(m => ({ default: m.HouseAccountsPage }))) },
  { id: "staff",        path: "/staff",        section: "Staff",        page: "Employees",
    element: lazy(() => import("@/pages/staff").then(m => ({ default: m.StaffPage }))) },
  { id: "staff-employees", path: "/staff/employees", section: "Staff", page: "Employees",
    element: lazy(() => import("@/pages/staff/employees").then(m => ({ default: m.StaffEmployeesPage }))) },
  { id: "staff-schedule", path: "/staff/schedule", section: "Staff", page: "Schedule",
    element: lazy(() => import("@/pages/staff/schedule").then(m => ({ default: m.StaffSchedulePage }))) },
  { id: "staff-attendance", path: "/staff/attendance", section: "Staff", page: "Attendance",
    element: lazy(() => import("@/pages/staff/attendance").then(m => ({ default: m.StaffAttendancePage }))) },
  { id: "staff-tips",   path: "/staff/tips",   section: "Staff",        page: "Tips",
    element: lazy(() => import("@/pages/staff/tips").then(m => ({ default: m.StaffTipsPage }))) },
  { id: "staff-payroll", path: "/staff/payroll", section: "Staff",     page: "Payroll Inputs",
    element: lazy(() => import("@/pages/staff/payroll").then(m => ({ default: m.StaffPayrollPage }))) },
  { id: "reports",      path: "/reports",      section: "Reports",      page: "Sales",
    element: lazy(() => import("@/pages/reports").then(m => ({ default: m.ReportsPage }))) },
  { id: "reports-sales", path: "/reports/sales", section: "Reports", page: "Sales",
    element: lazy(() => import("@/pages/reports/sales").then(m => ({ default: m.SalesPage }))) },
  { id: "reports-margin", path: "/reports/margin", section: "Reports", page: "Costs & Margin",
    element: lazy(() => import("@/pages/reports/margin").then(m => ({ default: m.MarginPage }))) },
  { id: "reports-channels", path: "/reports/channels", section: "Reports", page: "Channels",
    element: lazy(() => import("@/pages/reports/channels").then(m => ({ default: m.ChannelsPage }))) },
  { id: "reports-customers", path: "/reports/customers", section: "Reports", page: "Customers",
    element: lazy(() => import("@/pages/reports/customers").then(m => ({ default: m.CustomersPage }))) },
  { id: "reports-compliance", path: "/reports/compliance", section: "Reports", page: "Compliance",
    element: lazy(() => import("@/pages/reports/compliance").then(m => ({ default: m.CompliancePage }))) },
  { id: "reports-scheduled", path: "/reports/scheduled", section: "Reports", page: "Scheduled Reports",
    element: lazy(() => import("@/pages/reports/scheduled").then(m => ({ default: m.ScheduledPage }))) },
  { id: "settings",     path: "/settings",     section: "Settings",     page: "Integrations",
    element: lazy(() => import("@/pages/settings").then(m => ({ default: m.SettingsPage }))) },
  { id: "settings-businesses", path: "/settings/businesses", section: "Settings", page: "My Businesses",
    element: lazy(() => import("@/pages/settings/businesses").then(m => ({ default: m.BusinessesSettingsPage }))) },
  { id: "settings-businesses-new", path: "/settings/businesses/new", section: "Settings", page: "Create a New Business",
    element: lazy(() => import("@/pages/settings/businesses/create").then(m => ({ default: m.CreateBusinessPage }))) },
  { id: "settings-business", path: "/settings/business", section: "Settings", page: "Business & Legal Entities",
    element: lazy(() => import("@/pages/settings/business").then(m => ({ default: m.BusinessSettingsPage }))) },
  { id: "settings-branches", path: "/settings/branches", section: "Settings", page: "Branches & Sections",
    element: lazy(() => import("@/pages/settings/branches").then(m => ({ default: m.BranchesSettingsPage }))) },
  { id: "settings-devices", path: "/settings/devices", section: "Settings", page: "Devices & Printers",
    element: lazy(() => import("@/pages/settings/devices").then(m => ({ default: m.DevicesSettingsPage }))) },
  { id: "settings-roles", path: "/settings/roles", section: "Settings", page: "Roles & Permissions",
    element: lazy(() => import("@/pages/settings/roles").then(m => ({ default: m.RolesSettingsPage }))) },
  { id: "settings-tax", path: "/settings/tax", section: "Settings", page: "Tax Profile",
    element: lazy(() => import("@/pages/settings/tax").then(m => ({ default: m.TaxSettingsPage }))) },
  { id: "settings-modules", path: "/settings/modules", section: "Settings", page: "Restaurant Type & Modules",
    element: lazy(() => import("@/pages/settings/modules").then(m => ({ default: m.ModulesSettingsPage }))) },
  { id: "settings-integrations", path: "/settings/integrations", section: "Settings", page: "Integrations",
    element: lazy(() => import("@/pages/settings/integrations").then(m => ({ default: m.IntegrationsSettingsPage }))) },
  { id: "login",        path: "/login",        section: "Account",     page: "Sign in",
    element: lazy(() => import("@/pages/login").then(m => ({ default: m.LoginPage }))) },
  { id: "signup",       path: "/signup",       section: "Account",     page: "Create account",
    element: lazy(() => import("@/pages/signup").then(m => ({ default: m.SignUpPage }))) },
];
