import { lazy, type LazyExoticComponent, type ComponentType } from "react";

export interface AppRoute {
  id: string; // matches the sidebar group id
  path: string; // react-router path
  section: string; // breadcrumb: left side
  page: string; // breadcrumb: right side
  element: LazyExoticComponent<ComponentType>;
}

export const routes: AppRoute[] = [
  { id: "dashboard",    path: "/",             section: "Dashboard",    page: "Overview",
    element: lazy(() => import("@/pages/dashboard").then(m => ({ default: m.DashboardPage }))) },
  { id: "orders",       path: "/orders",       section: "Orders",       page: "Live Orders",
    element: lazy(() => import("@/pages/orders-list").then(m => ({ default: m.OrdersListPage }))) },
  { id: "kds",          path: "/kds",          section: "Orders",       page: "Kitchen Display",
    element: lazy(() => import("@/pages/kds").then(m => ({ default: m.KdsPage }))) },
  { id: "reservations", path: "/reservations", section: "Reservations", page: "Reservations",
    element: lazy(() => import("@/pages/reservations").then(m => ({ default: m.ReservationsPage }))) },
  { id: "reservations-new", path: "/reservations/new", section: "Reservations", page: "Guest Reservation",
    element: lazy(() => import("@/pages/reservations/new").then(m => ({ default: m.NewReservationPage }))) },
  { id: "reservations-floor-plan", path: "/reservations/floor-plan", section: "Floor Plan", page: "Live Floor Plan",
    element: lazy(() => import("@/pages/reservations/floor-plan").then(m => ({ default: m.LiveFloorPlanPage }))) },
  { id: "reservations-floor-plan-builder", path: "/reservations/floor-plan/builder", section: "Floor Plan", page: "Floor Plan Builder",
    element: lazy(() => import("@/pages/reservations/floor-plan/builder").then(m => ({ default: m.FloorPlanBuilderPage }))) },
  { id: "reservations-floor-plan-quick", path: "/reservations/floor-plan/builder/quick", section: "Floor Plan", page: "Quick Box Layout",
    element: lazy(() => import("@/pages/reservations/floor-plan/builder/quick").then(m => ({ default: m.QuickBoxLayoutPage }))) },
  { id: "reservations-floor-plan-scratch", path: "/reservations/floor-plan/builder/scratch", section: "Floor Plan", page: "Build From Scratch",
    element: lazy(() => import("@/pages/reservations/floor-plan/builder/scratch").then(m => ({ default: m.BuildFromScratchPage }))) },
  { id: "reservations-waitlist", path: "/reservations/waitlist", section: "Reservations", page: "Waitlist",
    element: lazy(() => import("@/pages/reservations/waitlist").then(m => ({ default: m.WaitlistPage }))) },
  { id: "reservations-waitlist-seat", path: "/reservations/waitlist/:entryId/seat", section: "Waitlist", page: "Seat Guest",
    element: lazy(() => import("@/pages/reservations/waitlist/seat").then(m => ({ default: m.SeatGuestPage }))) },
  { id: "menu",         path: "/menu",         section: "Menu",         page: "Menu",
    element: lazy(() => import("@/pages/menu/library").then(m => ({ default: m.MenuLibraryPage }))) },
  { id: "menu-new",     path: "/menu/new",     section: "Menu",         page: "Create New Menu",
    element: lazy(() => import("@/pages/menu/new").then(m => ({ default: m.CreateMenuPage }))) },
  { id: "menu-import",  path: "/menu/import",  section: "Menu",         page: "Import Menu",
    element: lazy(() => import("@/pages/menu/import").then(m => ({ default: m.ImportMenuPage }))) },
  { id: "menu-new-scratch", path: "/menu/new/scratch", section: "Menu",   page: "Create New Menu",
    element: lazy(() => import("@/pages/menu/build").then(m => ({ default: m.NewMenuRedirect }))) },
  { id: "menu-build",   path: "/menu/:menuId/build/*", section: "Menu",   page: "Menu Builder",
    element: lazy(() => import("@/pages/menu/build").then(m => ({ default: m.MenuBuilderPage }))) },
  { id: "public-link", path: "/public-link", section: "Storefront", page: "Public Link Builder",
    element: lazy(() => import("@/pages/public-link").then(m => ({ default: m.PublicLinkBuilderPage }))) },
  { id: "customers",    path: "/customers",    section: "Customers",    page: "Customer List",
    element: lazy(() => import("@/pages/customers").then(m => ({ default: m.CustomersPage }))) },
  { id: "customer-detail", path: "/customers/:id", section: "Customers", page: "Customer Profile",
    element: lazy(() => import("@/pages/customers/detail").then(m => ({ default: m.CustomerDetailPage }))) },
  { id: "finance",      path: "/finance",      section: "Finance",      page: "Payments & ZATCA",
    element: lazy(() => import("@/pages/finance").then(m => ({ default: m.FinancePage }))) },
  { id: "finance-payments", path: "/finance/payments", section: "Finance", page: "Payments & Transactions",
    element: lazy(() => import("@/pages/finance/payments").then(m => ({ default: m.PaymentsPage }))) },
  { id: "staff",        path: "/staff",        section: "Staff",        page: "Staff",
    element: lazy(() => import("@/pages/staff").then(m => ({ default: m.StaffPage }))) },
  { id: "settings",     path: "/settings",     section: "Settings",     page: "Business & Legal Entities",
    element: lazy(() => import("@/pages/settings").then(m => ({ default: m.SettingsPage }))) },
  { id: "settings-business", path: "/settings/business", section: "Settings", page: "Business & Legal Entities",
    element: lazy(() => import("@/pages/settings/business").then(m => ({ default: m.BusinessSettingsPage }))) },
  { id: "settings-branches", path: "/settings/branches", section: "Settings", page: "Branches & Sections",
    element: lazy(() => import("@/pages/settings/branches").then(m => ({ default: m.BranchesSettingsPage }))) },
  { id: "settings-devices", path: "/settings/devices", section: "Settings", page: "Devices & Printers",
    element: lazy(() => import("@/pages/settings/devices").then(m => ({ default: m.DevicesSettingsPage }))) },
  { id: "settings-roles", path: "/settings/roles", section: "Settings", page: "Roles & Permissions",
    element: lazy(() => import("@/pages/settings/roles").then(m => ({ default: m.RolesSettingsPage }))) },
  { id: "settings-tax", path: "/settings/tax", section: "Settings", page: "Tax Profile",
    element: lazy(() => import("@/pages/settings/tax").then(m => ({ default: m.TaxSettingsPage }))) },
  { id: "settings-modules", path: "/settings/modules", section: "Settings", page: "Restaurant Type & Modules",
    element: lazy(() => import("@/pages/settings/modules").then(m => ({ default: m.ModulesSettingsPage }))) },
  { id: "login",       path: "/login",        section: "Account",     page: "Sign in",
    element: lazy(() => import("@/pages/login").then(m => ({ default: m.LoginPage }))) },
  { id: "signup",       path: "/signup",       section: "Account",     page: "Create account",
    element: lazy(() => import("@/pages/signup").then(m => ({ default: m.SignUpPage }))) },
];
