// Strings for the plan-management, edit-lock, zones, grid, version and
// settings screens. They live beside the screens instead of in packages/i18n
// because that package is owned elsewhere; move them into the locale files
// (under the same `floorPlan.admin.*` keys) when it is next opened.
import { useCallback } from "react";
import { useI18n } from "@/app/providers/i18n-provider";

const en = {
  "summary.plans": "Plans",
  "summary.spots": "Live tables",
  "summary.capacity": "Live seats",
  "plans.title": "Your floor plans",
  "plans.subtitle": "Every plan this business has. The one marked “In editor” is what the builder and live floor use.",
  "plans.showArchived": "Show archived",
  "plans.loading": "Loading plans…",
  "plans.loadFailed": "Couldn't load your plans.",
  "plans.retry": "Retry",
  "plans.empty": "No plans yet.",
  "plans.inEditor": "In editor",
  "plans.useInEditor": "Use in editor",
  "plans.actions": "Plan actions",
  "plans.details": "Edit details",
  "plans.duplicate": "Duplicate",
  "plans.archive": "Archive",
  "plans.restore": "Restore",
  "plans.delete": "Delete",
  "plans.deleteHint": "Only plans that were never published",
  "plans.stats": "Statistics",
  "plans.updated": "Updated {when}",
  "plans.tables": "{n} tables",
  "plans.seats": "{n} seats",
  "plans.version": "v{n} live",
  "badge.Draft": "Draft",
  "badge.Published": "Published",
  "badge.PublishedWithChanges": "Unpublished changes",
  "badge.Archived": "Archived",
  "details.title": "Plan details",
  "details.name": "Name",
  "details.description": "Description",
  "details.branch": "Branch ID",
  "details.branchHint": "Optional",
  "details.save": "Save",
  "details.saved": "Plan details saved",
  "duplicate.title": "Duplicate plan",
  "duplicate.body": "Copies every table, zone and drawing into a new draft plan.",
  "duplicate.name": "Name of the copy",
  "duplicate.copySuffix": "(copy)",
  "duplicate.confirm": "Duplicate",
  "duplicate.done": "Plan duplicated",
  "archive.title": "Archive this plan?",
  "archive.body": "It leaves the list and can't be edited until it is restored. Its history is kept.",
  "archive.done": "Plan archived",
  "restore.done": "Plan restored",
  "delete.title": "Delete this plan?",
  "delete.body": "This plan was never published, so it is removed for good along with its tables.",
  "delete.done": "Plan deleted",
  "stats.title": "Plan statistics",
  "stats.spotCount": "Tables",
  "stats.totalCapacity": "Seats",
  "stats.zoneCount": "Zones",
  "stats.blockedCount": "Blocked tables",
  "stats.walkInCapacity": "Walk-in seats",
  "stats.unzonedCount": "Tables without a zone",
  "stats.sceneElementCount": "Drawn elements",
  "stats.wallLengthMeters": "Wall length",
  "common.cancel": "Cancel",
  "common.close": "Close",
  "common.saving": "Saving…",
  "common.loading": "Loading…",
  "common.failed": "Something went wrong.",
  "conflict": "Someone else changed this in the meantime. Reload and try again.",
  "lock.heldAnon": "Someone else is editing this floor plan",
  "lock.heldBody": "Their lock runs until {when}. Changes you make now may clash with theirs.",
  "lock.takeOver": "Take over editing",
  "lock.back": "Back to floor plan",
  "lock.viewAnyway": "Look without editing",
  "lock.tookOver": "You're now the editor of this plan",
  "lock.lost": "Someone else took over editing this plan.",
  "grid.open": "Generate table grid",
  "grid.title": "Generate a grid of tables",
  "grid.body": "The server lays out numbered tables in rows and columns, skipping numbers already in use.",
  "grid.count": "Number of tables",
  "grid.columns": "Columns",
  "grid.spacing": "Spacing (m)",
  "grid.prefix": "Number prefix",
  "grid.start": "Start at",
  "grid.shape": "Shape",
  "grid.capacity": "Seats per table",
  "grid.preview": "Preview",
  "grid.previewing": "Previewing…",
  "grid.generate": "Generate {n} tables",
  "grid.generating": "Generating…",
  "grid.planned": "{n} tables will be placed",
  "grid.skipped": "Numbers skipped (already used): {list}",
  "grid.grows": "The canvas will grow to {w}m × {h}m to fit them.",
  "grid.done": "{n} tables added",
  "grid.needPreview": "Preview first to see where they land.",
  "spot.server": "Saved on server",
  "spot.zone": "Zone",
  "spot.noZone": "No zone",
  "spot.availability": "Availability",
  "spot.combining": "Joinable group",
  "spot.priority": "Priority",
  "spot.revision": "Revision",
  "spot.notSaved": "Not saved to the server yet.",
  "zones.moveUp": "Move zone up",
  "zones.moveDown": "Move zone down",
  "versions.view": "View",
  "versions.hide": "Hide",
  "versions.makeLive": "Make live",
  "versions.rollbackTitle": "Put version {n} back live?",
  "versions.rollbackBody": "Guests and hosts switch to this version right away. Your current draft is kept.",
  "versions.rollbackNotes": "Note (optional)",
  "versions.rolledBack": "Version {n} is live again",
  "versions.rollbackFailed": "Couldn't put that version live.",
  "versions.detailFailed": "Couldn't load that version.",
  "versions.zones": "Zones",
  "versions.tables": "Tables",
  "versions.capacity": "Seats",
  "versions.notes": "Notes",
  "versions.label": "Label",
  "versions.noZones": "No zones",
  "settings.open": "Floor plan settings",
  "settings.title": "Floor plan settings",
  "settings.tab.sizes": "Table sizes",
  "settings.tab.layers": "Drawing layers",
  "settings.tab.limits": "Limits",
  "settings.loadFailed": "Couldn't load settings.",
  "settings.saved": "Settings saved",
  "settings.save": "Save changes",
  "settings.reset": "Reset to defaults",
  "settings.resetTitle": "Reset floor plan settings?",
  "settings.resetBody": "Catalogs, table sizes, layers and limits go back to the platform defaults. Your plans are not changed.",
  "settings.resetDone": "Settings reset to defaults",
  "settings.shape": "Shape",
  "settings.preset": "Size",
  "settings.width": "Width (m)",
  "settings.height": "Height (m)",
  "settings.addPreset": "Add size",
  "settings.remove": "Remove",
  "settings.layerCode": "Code",
  "settings.layerLabel": "Label",
  "settings.visible": "Visible",
  "settings.locked": "Locked",
  "settings.max": "Max {n}",
  "limits.capacityCeiling": "Max seats per table",
  "limits.maxSpotsPerPlan": "Max tables per plan",
  "limits.maxZonesPerPlan": "Max zones per plan",
  "limits.maxPlansPerBusiness": "Max plans",
  "limits.maxSpotsPerGridAction": "Max tables per grid",
  "limits.editLockMinutes": "Edit lock (minutes)",
  "limits.cleaningMinutes": "Cleaning time (minutes)",
  "limits.reservedHoldMinutes": "Reserved hold (minutes)",
  "limits.minAisleMeters": "Min aisle (m)",
} as const;

export type AdminTextKey = keyof typeof en;

const ar: Record<AdminTextKey, string> = {
  "summary.plans": "المخططات",
  "summary.spots": "طاولات مباشرة",
  "summary.capacity": "مقاعد مباشرة",
  "plans.title": "مخططات الصالة",
  "plans.subtitle": "كل مخططات هذا النشاط. المخطط المعلَّم «في المحرر» هو ما يستخدمه المحرر والصالة المباشرة.",
  "plans.showArchived": "عرض المؤرشفة",
  "plans.loading": "جارٍ تحميل المخططات…",
  "plans.loadFailed": "تعذّر تحميل المخططات.",
  "plans.retry": "إعادة المحاولة",
  "plans.empty": "لا توجد مخططات بعد.",
  "plans.inEditor": "في المحرر",
  "plans.useInEditor": "استخدمه في المحرر",
  "plans.actions": "إجراءات المخطط",
  "plans.details": "تعديل التفاصيل",
  "plans.duplicate": "نسخ",
  "plans.archive": "أرشفة",
  "plans.restore": "استعادة",
  "plans.delete": "حذف",
  "plans.deleteHint": "للمخططات التي لم تُنشر أبدًا فقط",
  "plans.stats": "الإحصائيات",
  "plans.updated": "آخر تحديث {when}",
  "plans.tables": "{n} طاولة",
  "plans.seats": "{n} مقعد",
  "plans.version": "الإصدار {n} مباشر",
  "badge.Draft": "مسودة",
  "badge.Published": "منشور",
  "badge.PublishedWithChanges": "تغييرات غير منشورة",
  "badge.Archived": "مؤرشف",
  "details.title": "تفاصيل المخطط",
  "details.name": "الاسم",
  "details.description": "الوصف",
  "details.branch": "معرّف الفرع",
  "details.branchHint": "اختياري",
  "details.save": "حفظ",
  "details.saved": "تم حفظ تفاصيل المخطط",
  "duplicate.title": "نسخ المخطط",
  "duplicate.body": "ينسخ كل الطاولات والمناطق والرسومات في مخطط مسودة جديد.",
  "duplicate.name": "اسم النسخة",
  "duplicate.copySuffix": "(نسخة)",
  "duplicate.confirm": "نسخ",
  "duplicate.done": "تم نسخ المخطط",
  "archive.title": "أرشفة هذا المخطط؟",
  "archive.body": "سيختفي من القائمة ولن يمكن تعديله حتى تستعيده. يبقى سجله محفوظًا.",
  "archive.done": "تمت أرشفة المخطط",
  "restore.done": "تمت استعادة المخطط",
  "delete.title": "حذف هذا المخطط؟",
  "delete.body": "لم يُنشر هذا المخطط أبدًا، لذا سيُحذف نهائيًا مع طاولاته.",
  "delete.done": "تم حذف المخطط",
  "stats.title": "إحصائيات المخطط",
  "stats.spotCount": "الطاولات",
  "stats.totalCapacity": "المقاعد",
  "stats.zoneCount": "المناطق",
  "stats.blockedCount": "طاولات محجوبة",
  "stats.walkInCapacity": "مقاعد الحضور المباشر",
  "stats.unzonedCount": "طاولات بلا منطقة",
  "stats.sceneElementCount": "عناصر مرسومة",
  "stats.wallLengthMeters": "طول الجدران",
  "common.cancel": "إلغاء",
  "common.close": "إغلاق",
  "common.saving": "جارٍ الحفظ…",
  "common.loading": "جارٍ التحميل…",
  "common.failed": "حدث خطأ ما.",
  "conflict": "غيّر شخص آخر هذا في الأثناء. أعد التحميل وحاول مجددًا.",
  "lock.heldAnon": "شخص آخر يعدّل هذا المخطط الآن",
  "lock.heldBody": "ينتهي قفله في {when}. قد تتعارض تعديلاتك الآن مع تعديلاته.",
  "lock.takeOver": "تولَّ التعديل",
  "lock.back": "العودة للمخطط",
  "lock.viewAnyway": "تصفّح دون تعديل",
  "lock.tookOver": "أصبحت أنت محرر هذا المخطط",
  "lock.lost": "تولّى شخص آخر تعديل هذا المخطط.",
  "grid.open": "توليد شبكة طاولات",
  "grid.title": "توليد شبكة من الطاولات",
  "grid.body": "يرتّب الخادم طاولات مرقّمة في صفوف وأعمدة، متخطيًا الأرقام المستخدمة.",
  "grid.count": "عدد الطاولات",
  "grid.columns": "الأعمدة",
  "grid.spacing": "المسافة (م)",
  "grid.prefix": "بادئة الرقم",
  "grid.start": "ابدأ من",
  "grid.shape": "الشكل",
  "grid.capacity": "مقاعد لكل طاولة",
  "grid.preview": "معاينة",
  "grid.previewing": "جارٍ المعاينة…",
  "grid.generate": "توليد {n} طاولة",
  "grid.generating": "جارٍ التوليد…",
  "grid.planned": "سيتم وضع {n} طاولة",
  "grid.skipped": "أرقام متخطاة (مستخدمة): {list}",
  "grid.grows": "ستتسع المساحة إلى {w}م × {h}م لتتسع لها.",
  "grid.done": "تمت إضافة {n} طاولة",
  "grid.needPreview": "عاين أولًا لترى أين ستوضع.",
  "spot.server": "محفوظ على الخادم",
  "spot.zone": "المنطقة",
  "spot.noZone": "بلا منطقة",
  "spot.availability": "التوفر",
  "spot.combining": "مجموعة الدمج",
  "spot.priority": "الأولوية",
  "spot.revision": "المراجعة",
  "spot.notSaved": "لم يُحفظ على الخادم بعد.",
  "zones.moveUp": "تحريك المنطقة لأعلى",
  "zones.moveDown": "تحريك المنطقة لأسفل",
  "versions.view": "عرض",
  "versions.hide": "إخفاء",
  "versions.makeLive": "اجعله مباشرًا",
  "versions.rollbackTitle": "إعادة الإصدار {n} مباشرًا؟",
  "versions.rollbackBody": "سينتقل الضيوف والمضيفون إلى هذا الإصدار فورًا. تبقى مسودتك الحالية كما هي.",
  "versions.rollbackNotes": "ملاحظة (اختياري)",
  "versions.rolledBack": "الإصدار {n} مباشر من جديد",
  "versions.rollbackFailed": "تعذّر جعل هذا الإصدار مباشرًا.",
  "versions.detailFailed": "تعذّر تحميل هذا الإصدار.",
  "versions.zones": "المناطق",
  "versions.tables": "الطاولات",
  "versions.capacity": "المقاعد",
  "versions.notes": "ملاحظات",
  "versions.label": "العنوان",
  "versions.noZones": "لا توجد مناطق",
  "settings.open": "إعدادات مخطط الصالة",
  "settings.title": "إعدادات مخطط الصالة",
  "settings.tab.sizes": "أحجام الطاولات",
  "settings.tab.layers": "طبقات الرسم",
  "settings.tab.limits": "الحدود",
  "settings.loadFailed": "تعذّر تحميل الإعدادات.",
  "settings.saved": "تم حفظ الإعدادات",
  "settings.save": "حفظ التغييرات",
  "settings.reset": "استعادة الافتراضي",
  "settings.resetTitle": "استعادة إعدادات المخطط الافتراضية؟",
  "settings.resetBody": "تعود القوائم وأحجام الطاولات والطبقات والحدود إلى إعدادات المنصة الافتراضية. لا تتغير مخططاتك.",
  "settings.resetDone": "تمت استعادة الإعدادات الافتراضية",
  "settings.shape": "الشكل",
  "settings.preset": "الحجم",
  "settings.width": "العرض (م)",
  "settings.height": "الطول (م)",
  "settings.addPreset": "إضافة حجم",
  "settings.remove": "إزالة",
  "settings.layerCode": "الرمز",
  "settings.layerLabel": "الاسم",
  "settings.visible": "ظاهر",
  "settings.locked": "مقفل",
  "settings.max": "الحد {n}",
  "limits.capacityCeiling": "أقصى مقاعد للطاولة",
  "limits.maxSpotsPerPlan": "أقصى طاولات للمخطط",
  "limits.maxZonesPerPlan": "أقصى مناطق للمخطط",
  "limits.maxPlansPerBusiness": "أقصى عدد مخططات",
  "limits.maxSpotsPerGridAction": "أقصى طاولات للشبكة",
  "limits.editLockMinutes": "قفل التعديل (دقائق)",
  "limits.cleaningMinutes": "وقت التنظيف (دقائق)",
  "limits.reservedHoldMinutes": "مهلة الحجز (دقائق)",
  "limits.minAisleMeters": "أقل ممر (م)",
};

const dictionaries: Record<string, Record<AdminTextKey, string>> = { en, ar };

export type AdminT = (key: AdminTextKey, vars?: Record<string, string | number>) => string;

export function useAdminText(): AdminT {
  const { locale } = useI18n();
  return useCallback(
    (key, vars) => {
      let text: string = (dictionaries[locale] ?? en)[key] ?? en[key];
      if (vars) for (const [name, value] of Object.entries(vars)) text = text.split(`{${name}}`).join(String(value));
      return text;
    },
    [locale]
  );
}
